// articles.jsx — Contingut complet dels 7 capítols
// Cada array és la seqüència de blocs que es renderitza via renderChapter(blocks, lang).

export const ARTICLE_ORIGENS = [
  { kind: "section", t: { ca: "L'origen", es: "El origen", en: "The origin" } },
  { kind: "p", lead: true, t: {
    ca: "La història de la producció elèctrica a la desembocadura del Besòs comença el **1913**, quan s'inaugura la primera central tèrmica de cicle convencional alimentada amb carbó, propietat d'*Energía Eléctrica de Cataluña*.",
    es: "La historia de la producción eléctrica en la desembocadura del Besòs se remonta a **1913**, cuando se inauguró la primera central térmica de ciclo convencional alimentada con carbón, propiedad de *Energía Eléctrica de Cataluña*.",
    en: "The story of electrical production at the mouth of the Besòs begins in **1913**, when the first conventional-cycle coal-fired thermal power plant was inaugurated, owned by *Energía Eléctrica de Cataluña*.",
  }},
  { kind: "p", t: {
    ca: "Va ser la primera gran planta tèrmica construïda en aquesta zona i responia a la creixent necessitat d'electricitat d'una Barcelona en ple procés d'industrialització i expansió urbana a començaments del segle XX.",
    es: "Fue la primera gran planta térmica construida en esta zona y respondía a la creciente necesidad de electricidad de una Barcelona en pleno proceso de industrialización y expansión urbana a comienzos del siglo XX.",
    en: "It was the first major thermal plant built in this area and answered the growing electricity demand of a Barcelona undergoing rapid industrialization and urban expansion at the turn of the 20th century.",
  }},
  { kind: "figure", src: "assets/construccio-1971.jpg", num: "01", year: "c.1925", ratio: "wide",
    desc: {
      ca: "Primera central tèrmica del Besòs. Vista aèria amb les quatre xemeneies de maons originals, els horts circumdants i el moll de descàrrega de carbó que s'endinsava al mar.",
      es: "Primera central térmica del Besòs. Vista aérea con las cuatro chimeneas de ladrillo originales, las huertas circundantes y el muelle de descarga de carbón adentrándose en el mar.",
      en: "The first Besòs thermal plant. Aerial view of the four original brick chimneys, surrounding orchards, and the coal-unloading pier reaching into the sea.",
    },
    source: { ca: "Fons Històric Endesa", es: "Fondo Histórico Endesa", en: "Endesa Historical Archive" },
  },
  { kind: "section", t: { ca: "Tecnologia pionera", es: "Tecnología pionera", en: "Pioneering technology" } },
  { kind: "p", t: {
    ca: "La central va ser dissenyada per l'arquitecte **Eduard Ferrés** i construïda per Construccions i Paviments, utilitzant *formigó armat* i aplicant per primera vegada a Catalunya el sistema **Hennebique**.",
    es: "La central fue diseñada por el arquitecto **Eduard Ferrés** y construida por Construcciones y Pavimentos, utilizando *hormigón armado* y aplicando por primera vez en Cataluña el sistema **Hennebique**.",
    en: "The plant was designed by architect **Eduard Ferrés** and built by Construcciones y Pavimentos using *reinforced concrete* and applying — for the first time in Catalonia — the **Hennebique** system.",
  }},
  { kind: "p", t: {
    ca: "Les obres van començar l'abril de 1912 i la central es va connectar a la xarxa el **23 de març de 1913**. El projecte preveia vuit turboalternadors; en l'engegada només n'entraren en funcionament dos, de 7,5 MW cadascun. Un any més tard s'ampliava amb un grup de 15 MW.",
    es: "Las obras comenzaron en abril de 1912 y la central se conectó a la red el **23 de marzo de 1913**. El proyecto preveía ocho turboalternadores; en la puesta en marcha sólo entraron en funcionamiento dos, de 7,5 MW cada uno. Un año después se ampliaba con un grupo de 15 MW.",
    en: "Construction began in April 1912 and the plant was connected to the grid on **23 March 1913**. The original project foresaw eight turbo-alternators; only two went into operation initially, at 7.5 MW each. A year later, a 15 MW group was added.",
  }},
  { kind: "stats", head: { ca: "La primera central · 1913", es: "La primera central · 1913", en: "The first plant · 1913" },
    items: [
      { num: "30", unit: "MW",
        label: { ca: "Potència total",     es: "Potencia total",     en: "Total power" },
        desc:  { ca: "2 grups de 7,5 + 1 de 15.", es: "2 grupos de 7,5 + 1 de 15.", en: "Two 7.5 MW groups + one 15 MW." } },
      { num: "4",
        label: { ca: "Xemeneies de maons", es: "Chimeneas de ladrillo", en: "Brick chimneys" },
        desc:  { ca: "60 m d'alçada cadascuna.", es: "60 m de altura cada una.", en: "60 m tall each." } },
      { num: "16",
        label: { ca: "Generadors de vapor", es: "Generadores de vapor", en: "Steam generators" },
        desc:  { ca: "Sistema Delaunay-Belleville.", es: "Sistema Delaunay-Belleville.", en: "Delaunay-Belleville system." } },
      { num: "150", unit: "m",
        label: { ca: "Captació al mar", es: "Captación marina", en: "Sea intake" },
        desc:  { ca: "Tubs de ferro per al refredament.", es: "Tubos de hierro para refrigeración.", en: "Iron pipes for cooling." } },
    ],
  },
  { kind: "section", t: { ca: "La xarxa", es: "La red", en: "The grid" } },
  { kind: "p", t: {
    ca: "Un dels elements més destacats va ser la connexió amb la central hidroelèctrica de *Cabdella*, també d'EEC. Una línia d'alta tensió de **80 kV i 175 km** — la primera d'aquestes característiques a Catalunya — va convertir el Besòs en peça clau del sistema elèctric català.",
    es: "Uno de los elementos más destacados fue la conexión con la central hidroeléctrica de *Cabdella*, también de EEC. Una línea de alta tensión de **80 kV y 175 km** — la primera de estas características en Cataluña — convirtió al Besòs en pieza clave del sistema eléctrico catalán.",
    en: "One of the standout features was the connection to the *Cabdella* hydroelectric station, also owned by EEC. An **80 kV, 175 km** high-voltage line — the first of its kind in Catalonia — turned the Besòs plant into a keystone of the Catalan electrical system.",
  }},
  { kind: "quote",
    t: {
      ca: "La primera xarxa d'alta tensió de **175 quilòmetres** que va connectar *el Pirineu amb el mar*.",
      es: "La primera red de alta tensión de **175 kilómetros** que conectó *el Pirineo con el mar*.",
      en: "The first high-voltage grid of **175 kilometres** to connect *the Pyrenees with the sea*.",
    },
    cite: {
      ca: "— Línia Cabdella–Besòs · 80 kV · 1913",
      es: "— Línea Cabdella–Besòs · 80 kV · 1913",
      en: "— Cabdella–Besòs line · 80 kV · 1913",
    },
  },
  { kind: "figure", src: "assets/turbines-1988.jpg", num: "02", year: "c.1925", ratio: "wide",
    desc: {
      ca: "Interior de la sala de turbines. Setze generadors Delaunay-Belleville produïen el vapor a partir de la combustió de carbó britànic.",
      es: "Interior de la sala de turbinas. Dieciséis generadores Delaunay-Belleville producían el vapor a partir de la combustión de carbón británico.",
      en: "Inside the turbine hall. Sixteen Delaunay-Belleville generators produced steam from British coal combustion.",
    },
    source: { ca: "Fons Històric Endesa", es: "Fondo Histórico Endesa", en: "Endesa Historical Archive" },
  },
  { kind: "section", t: { ca: "Guerra i bombardeig", es: "Guerra y bombardeo", en: "War and bombing" } },
  { kind: "p", t: {
    ca: "L'activitat es va veure greument afectada durant la **Primera Guerra Mundial** pel bloqueig marítim que va dificultar l'abastament de carbó britànic. El 1923, la companyia va passar a mans de *Barcelona Traction* — coneguda com **la Canadenca**.",
    es: "La actividad se vio seriamente afectada durante la **Primera Guerra Mundial** por el bloqueo marítimo que dificultó el abastecimiento de carbón británico. En 1923, la compañía pasó a manos de *Barcelona Traction* — conocida como **la Canadiense**.",
    en: "Operations were severely affected during the **First World War** by the maritime blockade that disrupted British coal supplies. In 1923, the company passed to *Barcelona Traction* — popularly known as **the Canadian**.",
  }},
  { kind: "p", t: {
    ca: "Durant la Guerra Civil la central va adquirir gran importància estratègica: garantia el subministrament elèctric de Barcelona. Va ser bombardejada el **13 de novembre de 1938** per l'aviació italiana, causant **setze víctimes mortals**.",
    es: "Durante la Guerra Civil la central adquirió gran importancia estratégica: garantizaba el suministro eléctrico de Barcelona. Fue bombardeada el **13 de noviembre de 1938** por la aviación italiana, causando **dieciséis víctimas mortales**.",
    en: "During the Spanish Civil War the plant gained strategic importance: it kept Barcelona's electricity running. It was bombed on **13 November 1938** by Italian aviation, killing **sixteen people**.",
  }},
  { kind: "fact", t: {
    ca: "L'aviació italiana va bombardejar la central original durant la guerra civil, el 13 de novembre de 1938. **Mai es va recuperar dels danys.**",
    es: "La aviación italiana bombardeó la central original durante la guerra civil, el 13 de noviembre de 1938. **Nunca se repuso de los daños.**",
    en: "Italian aviation bombed the original plant during the civil war, on 13 November 1938. **It never recovered from the damage.**",
  }},
  { kind: "section", t: { ca: "Final d'una era", es: "Fin de una era", en: "End of an era" } },
  { kind: "p", t: {
    ca: "El 1939, durant la retirada republicana, part de les instal·lacions van ser volades; només quedà operatiu un grup de 7,5 MW. El **1948**, Barcelona Traction fou declarada en fallida i els seus actius passaren a la recent creada *Fuerzas Eléctricas de Cataluña, S.A.* (FECSA).",
    es: "En 1939, durante la retirada republicana, parte de las instalaciones fueron voladas; sólo quedó operativo un grupo de 7,5 MW. En **1948**, Barcelona Traction fue declarada en quiebra y sus activos pasaron a la recién creada *Fuerzas Eléctricas de Cataluña, S.A.* (FECSA).",
    en: "In 1939, during the Republican retreat, parts of the facility were blown up; only a 7.5 MW group remained operational. In **1948**, Barcelona Traction was declared bankrupt and its assets transferred to the newly created *Fuerzas Eléctricas de Cataluña, S.A.* (FECSA).",
  }},
  { kind: "p", t: {
    ca: "El **1954**, la primera tèrmica del Besòs deixava definitivament de funcionar. Era substituïda per noves instal·lacions més modernes, marcant el final d'una primera etapa i el principi del camí que conduiria, anys més tard, a la construcció de les Tres Xemeneies.",
    es: "En **1954**, la primera térmica del Besòs dejaba definitivamente de funcionar. Fue sustituida por nuevas instalaciones más modernas, marcando el final de una primera etapa y el inicio del camino que conduciría, años más tarde, a la construcción de las Tres Chimeneas.",
    en: "In **1954**, the first Besòs plant ceased operations definitively. It was replaced by newer facilities, marking the end of one era and the start of the road that would lead, years later, to the construction of the Three Chimneys.",
  }},
  { kind: "figure", src: "assets/aerea-1913.jpg", num: "03", year: "1912", ratio: "wide",
    desc: {
      ca: "Arc d'entrada de la central original, amb la inscripció **1912** gravada en la pedra. Després del bombardeig i el cessament, l'edifici va quedar en ruïnes — testimoni mut de la primera etapa.",
      es: "Arco de entrada de la central original, con la inscripción **1912** grabada en la piedra. Tras el bombardeo y el cese, el edificio quedó en ruinas — testimonio mudo de la primera etapa.",
      en: "Entrance arch of the original plant, with **1912** carved into the stone. After the bombing and the shutdown, the building fell into ruin — a mute witness to the first era.",
    },
    source: { ca: "Fons Històric Endesa", es: "Fondo Histórico Endesa", en: "Endesa Historical Archive" },
  },
];

export const ARTICLE_PRODUCCIO = [
  { kind: "section", t: { ca: "Demanda creixent", es: "Demanda creciente", en: "Growing demand" } },
  { kind: "p", lead: true, t: {
    ca: "A finals dels anys 50, l'àrea metropolitana de Barcelona vivia un creixement industrial i demogràfic accelerat. El sistema hidràulic ja no era suficient per cobrir-ne les necessitats energètiques.",
    es: "A finales de los años 50, el área metropolitana de Barcelona vivía un crecimiento industrial y demográfico acelerado. El sistema hidráulico ya no era suficiente para cubrir sus necesidades energéticas.",
    en: "By the late 1950s, the Barcelona metropolitan area was undergoing accelerated industrial and demographic growth. The hydraulic system alone could no longer cover energy demand.",
  }},
  { kind: "p", t: {
    ca: "FECSA va decidir invertir en noves instal·lacions termoelèctriques. **Badalona I** es va inaugurar el **1959**, concebuda inicialment com a central de reserva. El fort increment del consum va fer que ràpidament s'integrés com a instal·lació activa.",
    es: "FECSA decidió invertir en nuevas instalaciones termoeléctricas. **Badalona I** se inauguró en **1959**, concebida inicialmente como central de reserva. El fuerte incremento del consumo hizo que rápidamente se integrara como instalación activa.",
    en: "FECSA decided to invest in new thermoelectric facilities. **Badalona I** opened in **1959**, initially conceived as a reserve plant. The sharp rise in consumption soon turned it into an active installation.",
  }},
  { kind: "section", t: { ca: "Badalona II", es: "Badalona II", en: "Badalona II" } },
  { kind: "p", t: {
    ca: "El **1965**, FECSA va ampliar la capacitat amb la central **Badalona II**, alimentada amb fueloil i amb una potència de **320 MW**. Tecnologia més avançada però amb un cost ambiental considerable: les emissions van intensificar les crítiques veïnals.",
    es: "En **1965**, FECSA amplió la capacidad con la central **Badalona II**, alimentada con fuelóleo y con una potencia de **320 MW**. Tecnología más avanzada pero con un coste ambiental considerable: las emisiones intensificaron las críticas vecinales.",
    en: "In **1965**, FECSA expanded capacity with **Badalona II**, fuel-oil powered and rated at **320 MW**. More advanced technology, but with a high environmental cost: emissions intensified neighborhood complaints.",
  }},
  { kind: "fact", t: {
    ca: "Les instal·lacions presentaven un estil industrial funcional. La següent central es projectaria en un estil **brutalista**, esdevenint l'edifici més alt del Mediterrani dins la seva tipologia.",
    es: "Las instalaciones presentaban un estilo industrial funcional. La siguiente central se proyectaría en un estilo **brutalista**, convirtiéndose en el edificio más alto del Mediterráneo dentro de su tipología.",
    en: "The facilities had a functional industrial style. The next plant would be designed in a **Brutalist** style, becoming the tallest building of its kind in the Mediterranean.",
  }},
  { kind: "figure", src: "assets/construccio-1971-b.jpg", num: "01", year: "1971-1976", ratio: "wide",
    desc: {
      ca: "Construcció dels grups generadors de la nova central. Les tres torres de formigó armat creixen sobre l'antic emplaçament, encara amb les grues a sobre.",
      es: "Construcción de los grupos generadores de la nueva central. Las tres torres de hormigón armado crecen sobre el antiguo emplazamiento, todavía con las grúas encima.",
      en: "Construction of the new plant's generator blocks. The three reinforced-concrete towers rise on the former site, still with cranes overhead.",
    },
    source: { ca: "Fons Històric Endesa", es: "Fondo Histórico Endesa", en: "Endesa Historical Archive" },
  },
  { kind: "section", t: { ca: "Les Tres Xemeneies", es: "Las Tres Chimeneas", en: "The Three Chimneys" } },
  { kind: "p", t: {
    ca: "El **1971**, FECSA va iniciar la construcció d'una nova central tèrmica en el mateix lloc on havia funcionat la primera. *San Adrián I* es va construir entre 1971 i 1973; *San Adrián II* entre 1972 i 1974. Un tercer bloc — *San Adrián III* — es va completar entre 1975 i 1976.",
    es: "En **1971**, FECSA inició la construcción de una nueva central térmica en el mismo lugar donde había funcionado la primera. *San Adrián I* se construyó entre 1971 y 1973; *San Adrián II* entre 1972 y 1974. Un tercer bloque — *San Adrián III* — se completó entre 1975 y 1976.",
    en: "In **1971**, FECSA started construction of a new thermal plant on the same site where the first had stood. *San Adrián I* was built 1971–1973; *San Adrián II* in parallel, 1972–1974. A third block — *San Adrián III* — was completed 1975–1976.",
  }},
  { kind: "p", t: {
    ca: "Cada bloc tenia una potència de **350 MW**. Plegats sumaven **1.050 MW**, comparable a la producció d'una central nuclear convencional.",
    es: "Cada bloque tenía una potencia de **350 MW**. Juntos sumaban **1.050 MW**, comparable a la producción de una central nuclear convencional.",
    en: "Each block was rated at **350 MW**. Together they reached **1,050 MW** — comparable to a conventional nuclear plant.",
  }},
  { kind: "stats", head: { ca: "L'escala de la planta", es: "La escala de la planta", en: "Plant scale" },
    items: [
      { num: "1.050", unit: "MW", label: { ca: "Potència total", es: "Potencia total", en: "Total power" }, desc: { ca: "Equivalent a una nuclear.", es: "Equivalente a una nuclear.", en: "Equivalent to a nuclear plant." } },
      { num: "200", unit: "m", label: { ca: "Alçada xemeneies", es: "Altura chimeneas", en: "Chimney height" }, desc: { ca: "Visibles des de tot el Besòs.", es: "Visibles desde todo el Besòs.", en: "Visible across the entire Besòs." } },
      { num: "350", unit: "MW", label: { ca: "Per bloc", es: "Por bloque", en: "Per block" }, desc: { ca: "3 grups generadors.", es: "3 grupos generadores.", en: "Three generator groups." } },
      { num: "30", unit: "%", label: { ca: "Consum català", es: "Consumo catalán", en: "Catalan demand" }, desc: { ca: "En els pics de demanda.", es: "En los picos de demanda.", en: "At peak demand." } },
    ],
  },
  { kind: "figure", video: "assets/video-chimneys.mov", poster: "assets/actual-01.jpg",
    num: "02",
    desc: {
      ca: "Vídeo: les Tres Xemeneies. Sistema constructiu de formigó armat, alçada de 200 metres, estil brutalista.",
      es: "Vídeo: las Tres Chimeneas. Sistema constructivo de hormigón armado, altura de 200 metros, estilo brutalista.",
      en: "Video: the Three Chimneys. Reinforced concrete construction, 200 metres tall, Brutalist style.",
    },
    source: { ca: "Arxiu audiovisual actual", es: "Archivo audiovisual actual", en: "Contemporary video archive" },
  },
  { kind: "section", t: { ca: "Asimetria forçada", es: "Asimetría forzada", en: "Forced asymmetry" } },
  { kind: "p", t: {
    ca: "Inicialment, la instal·lació es va projectar amb **només dues xemeneies**. L'augment imprevist de la demanda va motivar la incorporació d'una tercera turbina. Al no estar contemplada en els plànols originals, va haver d'adaptar-se a un terreny diferent.",
    es: "Inicialmente, la instalación se proyectó con **sólo dos chimeneas**. El aumento imprevisto de la demanda motivó la incorporación de una tercera turbina. Al no estar contemplada en los planos originales, hubo que adaptarla a un terreno distinto.",
    en: "The facility was initially planned with **only two chimneys**. An unexpected demand surge prompted the addition of a third turbine. As it wasn't in the original plans, it had to be adapted to a different plot.",
  }},
  { kind: "fact", t: {
    ca: "Les xemeneies **no són equidistants**: 53 metres separen la primera de la segona i 63 metres, la segona de la tercera. La tercera va haver de moure's per limitacions del terreny.",
    es: "Las chimeneas **no son equidistantes**: 53 metros separan la primera de la segunda y 63 metros, la segunda de la tercera. La tercera tuvo que desplazarse por limitaciones del terreno.",
    en: "The chimneys are **not equidistant**: 53 metres between the first and second, 63 metres between the second and third. The third had to be relocated due to site constraints.",
  }},
  { kind: "section", t: { ca: "L'episodi del 3 d'abril", es: "El episodio del 3 de abril", en: "The 3 April incident" } },
  { kind: "p", t: {
    ca: "Durant la construcció, les tensions laborals van derivar en conflictes sindicals. El **3 d'abril de 1973**, en plena obra del primer bloc, una protesta de treballadors va ser dispersada per la policia franquista amb trets.",
    es: "Durante la construcción, las tensiones laborales derivaron en conflictos sindicales. El **3 de abril de 1973**, en plena obra del primer bloque, una protesta de trabajadores fue dispersada por la policía franquista con disparos.",
    en: "During construction, labour tensions led to union conflicts. On **3 April 1973**, in the middle of the first block's works, a workers' protest was dispersed by Francoist police with gunfire.",
  }},
  { kind: "p", t: {
    ca: "L'obrer **Manuel Fernández Márquez**, de 27 anys, va morir aquell dia. Un altre treballador i diversos agents van resultar ferits. L'episodi va quedar com un punt clau de la confrontació social al voltant de l'obra.",
    es: "El obrero **Manuel Fernández Márquez**, de 27 años, murió aquel día. Otro trabajador y varios agentes resultaron heridos. El episodio quedó como un punto clave de la confrontación social en torno a la obra.",
    en: "Worker **Manuel Fernández Márquez**, 27, was killed that day. Another worker and several officers were injured. The incident remained a key moment of social confrontation around the construction.",
  }},
  { kind: "fact", t: {
    ca: "La construcció va donar feina a un gran nombre de persones, moltes d'elles **emigrades del sud d'Espanya** en cerca de treball. Va contribuir notablement al desenvolupament econòmic de l'àrea metropolitana.",
    es: "La construcción dio trabajo a un gran número de personas, muchas de ellas **emigradas del sur de España** en busca de empleo. Contribuyó notablemente al desarrollo económico del área metropolitana.",
    en: "Construction employed a large workforce, many of whom had **migrated from southern Spain** in search of work. It contributed significantly to the metropolitan area's economic development.",
  }},
  { kind: "quote",
    t: {
      ca: "Tres blocs, **1.050 MW**, vora *57.000 tones* anuals de diòxid de sofre.",
      es: "Tres bloques, **1.050 MW**, alrededor de *57.000 toneladas* anuales de dióxido de azufre.",
      en: "Three blocks, **1,050 MW**, some *57,000 tonnes* of sulfur dioxide per year.",
    },
    cite: {
      ca: "— Operació de les Tres Xemeneies · 1976-2011",
      es: "— Operación de las Tres Chimeneas · 1976-2011",
      en: "— Three Chimneys in operation · 1976-2011",
    },
  },
  { kind: "section", t: { ca: "Funcionament", es: "Funcionamiento", en: "How it ran" } },
  { kind: "p", t: {
    ca: "Tot i la potència elevada, les Tres Xemeneies no funcionaven de manera contínua. Operaven com a centrals **supletòries** dins el sistema elèctric català, activant-se en els pics de demanda i podent arribar a subministrar **entre el 25 i el 30 % del consum** de Catalunya.",
    es: "A pesar de la elevada potencia, las Tres Chimeneas no funcionaban de manera continua. Operaban como centrales **supletorias** dentro del sistema eléctrico catalán, activándose en los picos de demanda y pudiendo llegar a suministrar **entre el 25 y el 30 % del consumo** de Cataluña.",
    en: "Despite the high power rating, the Three Chimneys didn't run continuously. They operated as **back-up** stations within the Catalan grid, kicking in at demand peaks and supplying as much as **25–30 % of Catalonia's electricity** at those moments.",
  }},
  { kind: "p", t: {
    ca: "Aquesta era la seva grandesa i alhora la seva ferida: una força immensa que sostenia el país en els moments crítics, però que emetia tones de contaminants que recaurien sobre el barri.",
    es: "Esa era su grandeza y a la vez su herida: una fuerza inmensa que sostenía al país en los momentos críticos, pero que emitía toneladas de contaminantes que recaerían sobre el barrio.",
    en: "This was both its greatness and its wound: a vast force holding the country up in critical moments, but emitting tonnes of pollutants that would fall on the neighborhood.",
  }},
];

export const ARTICLE_TANCAMENT = [
  { kind: "section", t: { ca: "Zona contaminada", es: "Zona contaminada", en: "Polluted zone" } },
  { kind: "p", lead: true, t: {
    ca: "El **1983**, l'impacte ambiental acumulat al voltant de la central va arribar a un punt crític. Les autoritats van decretar oficialment Sant Adrià de Besòs com **«zona atmosfèrica contaminada»**.",
    es: "En **1983**, el impacto ambiental acumulado en torno a la central alcanzó un punto crítico. Las autoridades decretaron oficialmente Sant Adrià de Besòs como **«zona atmosférica contaminada»**.",
    en: "In **1983**, the accumulated environmental impact around the plant reached a critical point. The authorities formally declared Sant Adrià de Besòs an **\u201Catmospheric pollution zone\u201D**.",
  }},
  { kind: "p", t: {
    ca: "La declaració reconeixia que els nivells de pol·lució superaven els límits acceptables: emissions de partícules, sutge, diòxid de sofre. Comunitats senceres patien els efectes visibles — fanals, façanes i jardins coberts de pols negre.",
    es: "La declaración reconocía que los niveles de polución superaban los límites aceptables: emisiones de partículas, hollín, dióxido de azufre. Comunidades enteras sufrían los efectos visibles — farolas, fachadas y jardines cubiertos de polvo negro.",
    en: "The declaration acknowledged that pollution levels exceeded acceptable limits: particulates, soot, sulfur dioxide. Entire communities suffered the visible effects — street lamps, façades and gardens coated in black dust.",
  }},
  { kind: "figure", video: "assets/video-detail.mov", poster: "assets/actual-aeria.jpg",
    num: "01",
    desc: {
      ca: "Vídeo: detall actual de l'estructura. L'edifici buit després del cessament conserva la memòria del seu funcionament.",
      es: "Vídeo: detalle actual de la estructura. El edificio vacío tras el cese conserva la memoria de su funcionamiento.",
      en: "Video: contemporary detail of the structure. The empty building after shutdown retains the memory of its operation.",
    },
    source: { ca: "Arxiu audiovisual actual", es: "Archivo audiovisual actual", en: "Contemporary video archive" },
  },
  { kind: "section", t: { ca: "L'obsolescència", es: "La obsolescencia", en: "Obsolescence" } },
  { kind: "p", t: {
    ca: "A partir dels anys 90, la tecnologia de la central va començar a quedar enrere. Es va plantejar la possibilitat de migrar a un sistema de **cicle combinat** — menys contaminant i més eficient — que va portar finalment al tancament definitiu el **2011**.",
    es: "A partir de los años 90, la tecnología de la central empezó a quedarse atrás. Se planteó la posibilidad de migrar a un sistema de **ciclo combinado** — menos contaminante y más eficiente — que condujo finalmente al cierre definitivo en **2011**.",
    en: "From the 1990s onward, the plant's technology began to fall behind. A proposal to migrate to a **combined cycle** system — cleaner and more efficient — ultimately led to the definitive shutdown in **2011**.",
  }},
  { kind: "p", t: {
    ca: "Els últims anys, la planta operava de forma molt limitada, únicament com a central de suport en situacions excepcionals d'alta demanda energètica.",
    es: "En los últimos años, la planta operaba de forma muy limitada, únicamente como central de apoyo en situaciones excepcionales de alta demanda energética.",
    en: "In its final years the plant ran on a very limited basis, used only as a back-up in exceptional high-demand situations.",
  }},
  { kind: "stats", head: { ca: "Per què va tancar", es: "Por qué cerró", en: "Why it closed" },
    items: [
      { num: "100", unit: "anys", label: { ca: "D'activitat", es: "De actividad", en: "Of activity" }, desc: { ca: "Cicle convencional carbó/fueloil.", es: "Ciclo convencional carbón/fuelóleo.", en: "Conventional coal/oil cycle." } },
      { num: "57k", unit: "t/any", label: { ca: "Emissions SO₂", es: "Emisiones SO₂", en: "SO₂ emissions" }, desc: { ca: "En operació contínua.", es: "En operación continua.", en: "Under continuous operation." } },
      { num: "UE", label: { ca: "Normativa", es: "Normativa", en: "Regulation" }, desc: { ca: "Endurida a partir dels 2000.", es: "Endurecida a partir de los 2000.", en: "Tightened from the 2000s." } },
      { num: "0", label: { ca: "Inversió", es: "Inversión", en: "Investment" }, desc: { ca: "Endesa descarta modernitzar-la.", es: "Endesa descarta modernizarla.", en: "Endesa declined to modernize it." } },
    ],
  },
  { kind: "section", t: { ca: "2011 · L'última volta", es: "2011 · La última vuelta", en: "2011 · The last turn" } },
  { kind: "p", t: {
    ca: "El **2011**, *Endesa* — propietària de la planta després dels processos de concentració del sector — va posar fi definitivament al funcionament de les Tres Xemeneies.",
    es: "En **2011**, *Endesa* — propietaria de la planta tras los procesos de concentración del sector — puso fin definitivamente al funcionamiento de las Tres Chimeneas.",
    en: "In **2011**, *Endesa* — owner of the plant after sector consolidation — definitively ended Three Chimneys' operations.",
  }},
  { kind: "p", t: {
    ca: "El tancament responia a tres factors: **obsolescència tecnològica**, **baixa rendibilitat econòmica** i el **nou marc normatiu europeu**, que exigia fortes inversions per reduir les emissions contaminants. Endesa va descartar-les.",
    es: "El cierre respondía a tres factores: **obsolescencia tecnológica**, **baja rentabilidad económica** y el **nuevo marco normativo europeo**, que exigía fuertes inversiones para reducir las emisiones contaminantes. Endesa las descartó.",
    en: "The closure was driven by three factors: **technological obsolescence**, **low economic profitability** and the **new European regulatory framework**, which demanded heavy investment to cut emissions. Endesa declined.",
  }},
  { kind: "quote",
    t: {
      ca: "Quan es va aturar l'última turbina es va tancar **una etapa històrica** de la producció elèctrica a la desembocadura del *Besòs*.",
      es: "Cuando se detuvo la última turbina se cerró **una etapa histórica** de la producción eléctrica en la desembocadura del *Besòs*.",
      en: "When the last turbine stopped, **a historic era** of electrical production at the mouth of the *Besòs* came to a close.",
    },
    cite: { ca: "— Endesa · 2011", es: "— Endesa · 2011", en: "— Endesa · 2011" },
  },
  { kind: "figure", src: "assets/actual-02.jpg", num: "02", ratio: "tall",
    desc: {
      ca: "Les xemeneies quietes. Després de gairebé un segle de funcionament, l'apagada va deixar el complex sense funció industrial.",
      es: "Las chimeneas quietas. Tras casi un siglo de funcionamiento, el apagado dejó el complejo sin función industrial.",
      en: "Chimneys at rest. After nearly a century of operation, the shutdown left the complex without an industrial purpose.",
    },
    source: { ca: "Arxiu fotogràfic actual", es: "Archivo fotográfico actual", en: "Contemporary photo archive" },
  },
  { kind: "section", t: { ca: "Després del cessament", es: "Tras el cese", en: "After the shutdown" } },
  { kind: "p", t: {
    ca: "Amb l'apagada de la central va començar el procés de desmantellament de les instal·lacions interiors. Però les **Tres Xemeneies van romandre dempeus** com a testimoni físic del passat industrial i energètic de Sant Adrià.",
    es: "Con el apagado de la central comenzó el proceso de desmantelamiento de las instalaciones interiores. Pero las **Tres Chimeneas permanecieron en pie** como testimonio físico del pasado industrial y energético de Sant Adrià.",
    en: "With the shutdown began the dismantling of the interior facilities. But the **Three Chimneys remained standing** as a physical witness to Sant Adrià's industrial and energy past.",
  }},
  { kind: "p", t: {
    ca: "La pregunta es traslladava ara al carrer: què en faríem? Era el moment de decidir si el complex es derrocava o es preservava. La resposta arribaria de la ciutadania.",
    es: "La pregunta se trasladaba ahora a la calle: ¿qué hacíamos con esto? Era el momento de decidir si el complejo se derribaba o se preservaba. La respuesta llegaría desde la ciudadanía.",
    en: "The question now moved to the street: what to do with this? It was time to decide whether to demolish or preserve. The answer would come from citizens.",
  }},
];

export const ARTICLE_REIVINDICACIO = [
  { kind: "section", t: { ca: "1966 · La primera protesta", es: "1966 · La primera protesta", en: "1966 · The first protest" } },
  { kind: "p", lead: true, t: {
    ca: "La història de la reivindicació veïnal comença molt abans del tancament. El **1966**, en ple règim franquista, més de mil persones — *majoritàriament dones* — sortiren al carrer contra **el «polsim negre»** que les xemeneies escampaven sobre el barri.",
    es: "La historia de la reivindicación vecinal comienza mucho antes del cierre. En **1966**, en pleno régimen franquista, más de mil personas — *mayoritariamente mujeres* — salieron a la calle contra **el «polvillo negro»** que las chimeneas esparcían sobre el barrio.",
    en: "The story of citizen mobilization starts long before the shutdown. In **1966**, under Franco's regime, more than a thousand people — *mostly women* — took to the streets against the **\u201Cblack soot\u201D** the chimneys scattered over the neighborhood.",
  }},
  { kind: "p", t: {
    ca: "Una manifestació poc habitual a l'Espanya de la dictadura, motivada per les molèsties ambientals: sutge a la roba estesa, partícules sobre els balcons, taques als cotxes aparcats.",
    es: "Una manifestación poco habitual en la España de la dictadura, motivada por las molestias ambientales: hollín en la ropa tendida, partículas sobre los balcones, manchas en los coches aparcados.",
    en: "An unusual demonstration in dictatorship-era Spain, driven by environmental nuisance: soot on hanging laundry, particles on balconies, stains on parked cars.",
  }},
  { kind: "fact", t: {
    ca: "Gràcies a la pressió ciutadana, les autoritats van haver de modificar el projecte de la nova central. Les xemeneies, inicialment projectades a 180 m, es van elevar fins als **200 m** per dispersar millor els contaminants.",
    es: "Gracias a la presión ciudadana, las autoridades tuvieron que modificar el proyecto de la nueva central. Las chimeneas, inicialmente proyectadas a 180 m, se elevaron hasta los **200 m** para dispersar mejor los contaminantes.",
    en: "Thanks to citizen pressure, the authorities had to modify the new plant's design. The chimneys, originally planned at 180 m, were raised to **200 m** to better disperse pollutants.",
  }},
  { kind: "figure", src: "assets/actual-03.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Vista de les xemeneies des del veïnat. El conjunt forma part de la identitat visual de Sant Adrià, Badalona i el Besòs.",
      es: "Vista de las chimeneas desde el vecindario. El conjunto forma parte de la identidad visual de Sant Adrià, Badalona y el Besòs.",
      en: "View of the chimneys from the neighborhood. The complex is part of the visual identity of Sant Adrià, Badalona and the Besòs.",
    },
    source: { ca: "Arxiu fotogràfic actual", es: "Archivo fotográfico actual", en: "Contemporary photo archive" },
  },
  { kind: "section", t: { ca: "2008 · El referèndum", es: "2008 · El referéndum", en: "2008 · The referendum" } },
  { kind: "p", t: {
    ca: "Quan, el **novembre de 2008**, la planta s'aproximava al tancament, la companyia elèctrica va plantejar enderrocar les xemeneies. L'Ajuntament va convocar una consulta popular per decidir-ne el futur.",
    es: "Cuando, en **noviembre de 2008**, la planta se aproximaba al cierre, la compañía eléctrica planteó derribar las chimeneas. El Ayuntamiento convocó una consulta popular para decidir su futuro.",
    en: "When, in **November 2008**, the plant approached closure, the electric company proposed demolishing the chimneys. The city council called a public referendum to decide their future.",
  }},
  { kind: "stats", head: { ca: "Resultats del referèndum", es: "Resultados del referéndum", en: "Referendum results" },
    items: [
      { num: "82", unit: "%", label: { ca: "A favor", es: "A favor", en: "In favor" }, desc: { ca: "Mantenir les xemeneies.", es: "Mantener las chimeneas.", en: "Keep the chimneys." } },
      { num: "406", label: { ca: "En contra", es: "En contra", en: "Against" }, desc: { ca: "D'un total de ~2.600 vots.", es: "De un total de ~2.600 votos.", en: "Out of ~2,600 votes." } },
      { num: "9,1", unit: "%", label: { ca: "Participació", es: "Participación", en: "Turnout" }, desc: { ca: "Sobre el cens electoral.", es: "Sobre el censo electoral.", en: "Of the electoral roll." } },
      { num: "Sí", label: { ca: "Vinculant", es: "Vinculante", en: "Binding" }, desc: { ca: "El resultat va frenar l'enderroc.", es: "El resultado frenó el derribo.", en: "The result halted demolition." } },
    ],
  },
  { kind: "p", t: {
    ca: "La consulta tenia caràcter vinculant. Tot i no definir un ús concret per a les estructures de formigó, sí va marcar una **voluntat popular clara** de preservar-les com a element identitari del paisatge urbà.",
    es: "La consulta tenía carácter vinculante. Aunque no definía un uso concreto para las estructuras de hormigón, sí marcó una **voluntad popular clara** de preservarlas como elemento identitario del paisaje urbano.",
    en: "The vote was binding. Although it didn't define a specific use for the concrete structures, it did mark a **clear popular will** to preserve them as a defining element of the urban landscape.",
  }},
  { kind: "quote",
    t: {
      ca: "Un *símbol* del paisatge urbà i de la **identitat col·lectiva** de Sant Adrià.",
      es: "Un *símbolo* del paisaje urbano y de la **identidad colectiva** de Sant Adrià.",
      en: "A *symbol* of the urban landscape and of the **collective identity** of Sant Adrià.",
    },
    cite: {
      ca: "— Plataforma per la Conservació de les Tres Xemeneies",
      es: "— Plataforma per la Conservació de les Tres Xemeneies",
      en: "— Platform for the Conservation of the Three Chimneys",
    },
  },
  { kind: "section", t: { ca: "2012 · L'expedient BCIL", es: "2012 · El expediente BCIL", en: "2012 · The BCIL file" } },
  { kind: "p", t: {
    ca: "Després d'anys de lluita veïnal, l'Ajuntament va iniciar el **2012** els tràmits administratius per protegir el conjunt com a *Bé Cultural d'Interès Local*. L'impuls va venir principalment de la **Plataforma per la Conservació de les Tres Xemeneies**.",
    es: "Tras años de lucha vecinal, el Ayuntamiento inició en **2012** los trámites administrativos para proteger el conjunto como *Bien Cultural de Interés Local*. El impulso vino principalmente de la **Plataforma per la Conservació de les Tres Xemeneies**.",
    en: "After years of neighborhood struggle, the city council started administrative procedures in **2012** to protect the complex as a *Local Cultural Heritage Asset*. The push came mainly from the **Platform for the Conservation of the Three Chimneys**.",
  }},
  { kind: "p", t: {
    ca: "Es van presentar sol·licituds formals, estudis i informes tècnics que justificaven la catalogació del conjunt: valor històric, arquitectònic, industrial i simbòlic dins el paisatge metropolità.",
    es: "Se presentaron solicitudes formales, estudios e informes técnicos que justificaban la catalogación del conjunto: valor histórico, arquitectónico, industrial y simbólico dentro del paisaje metropolitano.",
    en: "Formal requests, studies and technical reports were filed to justify the listing: historical, architectural, industrial and symbolic value within the metropolitan landscape.",
  }},
  { kind: "figure", src: "assets/actual-04.jpg", num: "02", ratio: "tall",
    desc: {
      ca: "Detall del formigó armat de les xemeneies. Patrimoni industrial preservat com a memòria del segle XX català.",
      es: "Detalle del hormigón armado de las chimeneas. Patrimonio industrial preservado como memoria del siglo XX catalán.",
      en: "Detail of the chimneys' reinforced concrete. Industrial heritage preserved as memory of 20th-century Catalonia.",
    },
    source: { ca: "Arxiu fotogràfic actual", es: "Archivo fotográfico actual", en: "Contemporary photo archive" },
  },
  { kind: "section", t: { ca: "2016 · La declaració definitiva", es: "2016 · La declaración definitiva", en: "2016 · The definitive listing" } },
  { kind: "p", t: {
    ca: "Quatre anys més tard, el **2016**, el ple de l'Ajuntament de Sant Adrià va aprovar definitivament la declaració de les Tres Xemeneies i de l'antiga sala de turbines com a **Bé Cultural d'Interès Local**.",
    es: "Cuatro años después, en **2016**, el pleno del Ayuntamiento de Sant Adrià aprobó definitivamente la declaración de las Tres Chimeneas y de la antigua sala de turbinas como **Bien Cultural de Interés Local**.",
    en: "Four years later, in **2016**, the Sant Adrià city council plenary definitively approved the listing of the Three Chimneys and the former turbine hall as a **Local Cultural Heritage Asset**.",
  }},
  { kind: "p", t: {
    ca: "Amb aquesta resolució es va culminar un procés iniciat quatre anys abans i es va atorgar **protecció jurídica efectiva** al conjunt, impedint-ne la demolició i assegurant-ne la preservació.",
    es: "Con esta resolución se culminó un proceso iniciado cuatro años antes y se otorgó **protección jurídica efectiva** al conjunto, impidiendo su demolición y asegurando su preservación.",
    en: "The resolution culminated a four-year process and granted **effective legal protection** to the complex, preventing its demolition and ensuring preservation.",
  }},
  { kind: "fact", t: {
    ca: "Una mobilització veïnal de **50 anys** — del «polsim negre» del 1966 al BCIL del 2016 — va salvar les xemeneies. Sense aquesta continuïtat, no quedaria res a preservar.",
    es: "Una movilización vecinal de **50 años** — del «polvillo negro» de 1966 al BCIL de 2016 — salvó las chimeneas. Sin esta continuidad, no quedaría nada que preservar.",
    en: "A neighborhood mobilization spanning **50 years** — from the 1966 \u201Cblack soot\u201D to the 2016 BCIL — saved the chimneys. Without that continuity, nothing would have remained to preserve.",
  }},
];


export const ARTICLE_FUTUR = [
  { kind: "section", t: { ca: "32 hectàrees", es: "32 hectáreas", en: "32 hectares" } },
  { kind: "p", lead: true, t: {
    ca: "Després del tancament i la protecció patrimonial, calia decidir què passaria amb les **32 hectàrees** del recinte. Una superfície gegantina al litoral metropolità — entre la via del ferrocarril i el mar.",
    es: "Tras el cierre y la protección patrimonial, había que decidir qué pasaría con las **32 hectáreas** del recinto. Una superficie gigantesca en el litoral metropolitano — entre la vía del ferrocarril y el mar.",
    en: "After the shutdown and the heritage listing, a decision had to be made about the site's **32 hectares**. A massive strip on the metropolitan seafront — between the railway and the sea.",
  }},
  { kind: "figure", src: "assets/render-pdu-aeria.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Vista general del projecte de futur. Les xemeneies preservades es converteixen en l'eix visual d'un nou barri litoral.",
      es: "Vista general del proyecto de futuro. Las chimeneas preservadas se convierten en el eje visual de un nuevo barrio litoral.",
      en: "Overview of the future project. The preserved chimneys become the visual axis of a new seafront district.",
    },
    source: { ca: "Render PDU 3X · Garcés De Seta Bonet", es: "Render PDU 3X · Garcés De Seta Bonet", en: "PDU 3X render · Garcés De Seta Bonet" },
  },
  { kind: "section", t: { ca: "2018 · Front Marítim del Besòs", es: "2018 · Front Marítim del Besòs", en: "2018 · Front Marítim del Besòs" } },
  { kind: "p", t: {
    ca: "A finals de **2018**, *Endesa Generación* i *Metrovacesa* van constituir la societat conjunta **Front Marítim del Besòs** amb la finalitat de planificar la transformació urbanística de la zona.",
    es: "A finales de **2018**, *Endesa Generación* y *Metrovacesa* constituyeron la sociedad conjunta **Front Marítim del Besòs** con la finalidad de planificar la transformación urbanística de la zona.",
    en: "In late **2018**, *Endesa Generación* and *Metrovacesa* formed the joint venture **Front Marítim del Besòs** to plan the urban transformation of the area.",
  }},
  { kind: "p", t: {
    ca: "Endesa havia heretat la major part dels terrenys després de l'adquisició de FECSA el 1996. Metrovacesa sumava al projecte una porció significativa de sòl per a desenvolupament residencial i terciari.",
    es: "Endesa había heredado la mayor parte de los terrenos tras la adquisición de FECSA en 1996. Metrovacesa sumaba al proyecto una porción significativa de suelo para desarrollo residencial y terciario.",
    en: "Endesa had inherited most of the land after acquiring FECSA in 1996. Metrovacesa added a significant share of land for residential and tertiary development.",
  }},
  { kind: "section", t: { ca: "2021 · El mur", es: "2021 · El muro", en: "2021 · The wall" } },
  { kind: "p", t: {
    ca: "El **8 de juliol de 2021**, els ajuntaments de Sant Adrià i Badalona van signar un conveni urbanístic amb Metrovacesa i Endesa per enderrocar el mur que separava els municipis i ampliar el carrer Eduard Maristany.",
    es: "El **8 de julio de 2021**, los ayuntamientos de Sant Adrià y Badalona firmaron un convenio urbanístico con Metrovacesa y Endesa para derribar el muro que separaba los municipios y ampliar la calle Eduard Maristany.",
    en: "On **8 July 2021**, the Sant Adrià and Badalona city councils signed an urban planning agreement with Metrovacesa and Endesa to tear down the wall separating the municipalities and widen Eduard Maristany Street.",
  }},
  { kind: "p", t: {
    ca: "L'acord va ampliar el carrer dels **9 als 20 metres**, amb noves voreres, carril bici, il·luminació i arbrat. Millor connectivitat, integració amb el passeig marítim, ciutat continuada.",
    es: "El acuerdo amplió la calle de los **9 a los 20 metros**, con nuevas aceras, carril bici, iluminación y arbolado. Mejor conectividad, integración con el paseo marítimo, ciudad continua.",
    en: "The agreement widened the street from **9 to 20 metres**, with new sidewalks, a bike lane, lighting and trees. Better connectivity, integration with the seafront promenade, a continuous city.",
  }},
  { kind: "figure", src: "assets/render-vialitat-a.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "Nova vialitat. El carrer Eduard Maristany ampliat, amb voreres generoses i carril bici, com a costura entre Sant Adrià i Badalona.",
      es: "Nueva vialidad. La calle Eduard Maristany ampliada, con aceras generosas y carril bici, como costura entre Sant Adrià y Badalona.",
      en: "New road layout. The widened Eduard Maristany Street, with generous sidewalks and a bike lane, stitching Sant Adrià and Badalona together.",
    },
    source: { ca: "Render Vialitat · Front Marítim", es: "Render Viario · Front Marítim", en: "Roads render · Front Marítim" },
  },
  { kind: "section", t: { ca: "2023 · L'aprovació del PDU", es: "2023 · La aprobación del PDU", en: "2023 · PDU approval" } },
  { kind: "p", t: {
    ca: "El **7 de març de 2023** es va aprovar el *Pla Director Urbanístic de les Tres Xemeneies*. Delimita i ordena un sector nou de 32 hectàrees al litoral, des de la desembocadura del Besòs fins al final de l'espai de les xemeneies.",
    es: "El **7 de marzo de 2023** se aprobó el *Plan Director Urbanístico de las Tres Chimeneas*. Delimita y ordena un sector nuevo de 32 hectáreas en el litoral, desde la desembocadura del Besòs hasta el final del espacio de las chimeneas.",
    en: "On **7 March 2023** the *Three Chimneys Urban Master Plan* was approved. It delimits and organizes a new 32-hectare seafront sector, from the mouth of the Besòs to the end of the chimneys' grounds.",
  }},
  { kind: "p", t: {
    ca: "A més, transforma mitjançant directrius urbanístiques un àmbit més ampli d'aproximadament **92 hectàrees**, on actualment hi ha magatzems i àrees industrials.",
    es: "Además, transforma mediante directrices urbanísticas un ámbito más amplio de aproximadamente **92 hectáreas**, donde actualmente hay almacenes y áreas industriales.",
    en: "It also transforms — via planning guidelines — a broader area of about **92 hectares**, currently occupied by warehouses and industrial zones.",
  }},
  { kind: "stats", head: { ca: "El PDU en xifres", es: "El PDU en cifras", en: "PDU in numbers" },
    items: [
      { num: "32",  unit: "ha", label: { ca: "Sector nou",    es: "Sector nuevo",    en: "New sector" },    desc: { ca: "Litoral metropolità.", es: "Litoral metropolitano.", en: "Metropolitan seafront." } },
      { num: "92",  unit: "ha", label: { ca: "Àmbit ampliat", es: "Ámbito ampliado", en: "Expanded area" }, desc: { ca: "Reordenació industrial.", es: "Reordenación industrial.", en: "Industrial rezoning." } },
      { num: "3",               label: { ca: "Municipis",      es: "Municipios",      en: "Municipalities" }, desc: { ca: "Sant Adrià, Badalona, Barcelona.", es: "Sant Adrià, Badalona, Barcelona.", en: "Sant Adrià, Badalona, Barcelona." } },
      { num: "1",               label: { ca: "PDU aprovat",    es: "PDU aprobado",    en: "PDU approved" }, desc: { ca: "Generalitat + Consorci + Ajuntaments.", es: "Generalitat + Consorci + Ayuntamientos.", en: "Catalan government + Consortium + councils." } },
    ],
  },
  { kind: "quote",
    t: {
      ca: "Un *nou barri litoral* construït al voltant del patrimoni industrial i d'un **hub audiovisual**.",
      es: "Un *nuevo barrio litoral* construido alrededor del patrimonio industrial y de un **hub audiovisual**.",
      en: "A *new seafront district* built around industrial heritage and an **audiovisual hub**.",
    },
    cite: {
      ca: "— PDU del Sector Tres Xemeneies · 2023",
      es: "— PDU del Sector Tres Chimeneas · 2023",
      en: "— Three Chimneys Sector Master Plan · 2023",
    },
  },
  { kind: "figure", src: "assets/render-parc-aeria.jpg", num: "03", ratio: "wide",
    desc: {
      ca: "Vista aèria del nou parc urbà. Les xemeneies com a eix vertical d'un espai verd a peu de mar.",
      es: "Vista aérea del nuevo parque urbano. Las chimeneas como eje vertical de un espacio verde a pie de mar.",
      en: "Aerial view of the new urban park. The chimneys as the vertical axis of a seaside green space.",
    },
    source: { ca: "Render Parc · Front Marítim", es: "Render Parque · Front Marítim", en: "Park render · Front Marítim" },
  },
  { kind: "section", t: { ca: "Catalunya Media City", es: "Catalunya Media City", en: "Catalunya Media City" } },
  { kind: "p", t: {
    ca: "El projecte cristal·litza en el PDU i en l'impuls de **Catalunya Media City**, un nou *hub* de l'audiovisual, el digital i el videojoc. La indústria que substituirà l'energia: continguts en lloc de carbó.",
    es: "El proyecto cristaliza en el PDU y en el impulso de **Catalunya Media City**, un nuevo *hub* del audiovisual, lo digital y el videojuego. La industria que sustituirá a la energía: contenidos en lugar de carbón.",
    en: "The project crystallizes in the PDU and the launch of **Catalunya Media City**, a new *hub* for audiovisual, digital and gaming industries. The industry that will replace energy: content instead of coal.",
  }},
  { kind: "p", t: {
    ca: "Catalunya Media City vol convertir el complex en un node de referència europea per a la producció audiovisual, integrat amb el barri, la platja i el parc.",
    es: "Catalunya Media City quiere convertir el complejo en un nodo de referencia europea para la producción audiovisual, integrado con el barrio, la playa y el parque.",
    en: "Catalunya Media City aims to turn the complex into a European reference hub for audiovisual production, integrated with the neighborhood, the beach and the park.",
  }},
];

export const ARTICLE_NAU_TURBINES = [
  { kind: "section", t: { ca: "L'epicentre del hub", es: "El epicentro del hub", en: "The hub's epicenter" } },
  { kind: "p", lead: true, t: {
    ca: "La **Nau de Turbines** serà l'epicentre de Catalunya Media City. L'espai on s'havien produït cinquanta anys d'electricitat es transforma ara en el cor del *hub* audiovisual.",
    es: "La **Nave de Turbinas** será el epicentro de Catalunya Media City. El espacio donde se habían producido cincuenta años de electricidad se transforma ahora en el corazón del *hub* audiovisual.",
    en: "The **Turbine Hall** will be the epicenter of Catalunya Media City. The space where fifty years of electricity were produced now becomes the heart of the audiovisual *hub*.",
  }},
  { kind: "p", t: {
    ca: "S'hi concentraran les activitats de **formació**, **innovació** i **experiència** del nou centre metropolità.",
    es: "Se concentrarán las actividades de **formación**, **innovación** y **experiencia** del nuevo centro metropolitano.",
    en: "It will house the **training**, **innovation** and **experience** activities of the new metropolitan center.",
  }},
  { kind: "figure", src: "assets/render-turbines-ext.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Vista exterior de la Nau de Turbines rehabilitada. La carcassa industrial conserva la seva memòria mentre incorpora nous usos.",
      es: "Vista exterior de la Nave de Turbinas rehabilitada. La carcasa industrial conserva su memoria mientras incorpora nuevos usos.",
      en: "Exterior view of the rehabilitated Turbine Hall. The industrial shell retains its memory while taking on new uses.",
    },
    source: { ca: "Render · Garcés De Seta Bonet + Marvel Architects", es: "Render · Garcés De Seta Bonet + Marvel Architects", en: "Render · Garcés De Seta Bonet + Marvel Architects" },
  },
  { kind: "section", t: { ca: "Els arquitectes", es: "Los arquitectos", en: "The architects" } },
  { kind: "p", t: {
    ca: "El projecte arquitectònic està sent realitzat conjuntament per dos despatxos: **Garcés De Seta Bonet** (Barcelona) i **Marvel Architects** (Nova York).",
    es: "El proyecto arquitectónico está siendo realizado conjuntamente por dos despachos: **Garcés De Seta Bonet** (Barcelona) y **Marvel Architects** (Nueva York).",
    en: "The architectural project is jointly developed by two studios: **Garcés De Seta Bonet** (Barcelona) and **Marvel Architects** (New York).",
  }},
  { kind: "p", t: {
    ca: "Una col·laboració internacional que aporta experiència en patrimoni industrial, rehabilitació arquitectònica i equipaments culturals contemporanis.",
    es: "Una colaboración internacional que aporta experiencia en patrimonio industrial, rehabilitación arquitectónica y equipamientos culturales contemporáneos.",
    en: "An international partnership bringing expertise in industrial heritage, architectural rehabilitation and contemporary cultural facilities.",
  }},
  { kind: "stats", head: { ca: "L'equip", es: "El equipo", en: "The team" },
    items: [
      { num: "2",   label: { ca: "Despatxos",      es: "Despachos",      en: "Studios" },             desc: { ca: "Internacionals.", es: "Internacionales.", en: "International." } },
      { num: "BCN", label: { ca: "Garcés·De·Seta·Bonet", es: "Garcés·De·Seta·Bonet", en: "Garcés·De·Seta·Bonet" }, desc: { ca: "Patrimoni i equipaments.", es: "Patrimonio y equipamientos.", en: "Heritage and facilities." } },
      { num: "NYC", label: { ca: "Marvel", es: "Marvel", en: "Marvel" },                              desc: { ca: "Arquitectura contemporània.", es: "Arquitectura contemporánea.", en: "Contemporary architecture." } },
      { num: "1",   label: { ca: "Concepte",       es: "Concepto",       en: "Concept" },             desc: { ca: "Cor del hub audiovisual.", es: "Corazón del hub audiovisual.", en: "Heart of the audiovisual hub." } },
    ],
  },
  { kind: "figure", src: "assets/render-turbines-int.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "Interior de la Nau de Turbines. Espai diàfan amb capacitat per acollir produccions, formació i activitats experiencials.",
      es: "Interior de la Nave de Turbinas. Espacio diáfano con capacidad para acoger producciones, formación y actividades experienciales.",
      en: "Inside the Turbine Hall. An open-plan space capable of hosting productions, training and experiential activities.",
    },
    source: { ca: "Render Interior · Nau de Turbines", es: "Render Interior · Nave de Turbinas", en: "Interior render · Turbine Hall" },
  },
  { kind: "section", t: { ca: "Tres usos, un cos", es: "Tres usos, un cuerpo", en: "Three uses, one body" } },
  { kind: "p", t: {
    ca: "La Nau s'organitzarà al voltant de tres grans funcions, totes complementàries dins del hub:",
    es: "La Nave se organizará en torno a tres grandes funciones, todas complementarias dentro del hub:",
    en: "The Hall will be organized around three major functions, all complementary within the hub:",
  }},
  { kind: "p", t: {
    ca: "**Formació.** Escola de referència per a perfils tècnics i creatius de l'audiovisual i el videojoc — des de tècnics de so fins a directors d'art digital.",
    es: "**Formación.** Escuela de referencia para perfiles técnicos y creativos del audiovisual y el videojuego — desde técnicos de sonido hasta directores de arte digital.",
    en: "**Training.** A reference school for technical and creative profiles in audiovisual and gaming — from sound engineers to digital art directors.",
  }},
  { kind: "p", t: {
    ca: "**Innovació.** Laboratoris, residències i espais de prototipatge on convergiran startups, indústria establerta i recerca universitària.",
    es: "**Innovación.** Laboratorios, residencias y espacios de prototipado donde convergerán startups, industria establecida e investigación universitaria.",
    en: "**Innovation.** Labs, residencies and prototyping spaces where startups, established industry and university research will converge.",
  }},
  { kind: "p", t: {
    ca: "**Experiència.** Equipament obert a la ciutadania: exposicions, esdeveniments i interaccions amb el que es produeix dins.",
    es: "**Experiencia.** Equipamiento abierto a la ciudadanía: exposiciones, eventos e interacciones con lo que se produce dentro.",
    en: "**Experience.** Open to citizens: exhibitions, events and interactions with what is produced inside.",
  }},
  { kind: "figure", src: "assets/render-turbines-ext-2.jpg", num: "03", ratio: "tall",
    desc: {
      ca: "Detall constructiu de la rehabilitació. La memòria del formigó armat es manté com a element estructural i narratiu.",
      es: "Detalle constructivo de la rehabilitación. La memoria del hormigón armado se mantiene como elemento estructural y narrativo.",
      en: "Construction detail of the rehabilitation. The reinforced concrete's memory remains as both structural and narrative element.",
    },
    source: { ca: "Render · Nau de Turbines", es: "Render · Nave de Turbinas", en: "Render · Turbine Hall" },
  },
  { kind: "quote",
    t: {
      ca: "Cinquanta anys produint *energia*. Els pròxims, produint **imatges, sons i idees**.",
      es: "Cincuenta años produciendo *energía*. Los próximos, produciendo **imágenes, sonidos e ideas**.",
      en: "Fifty years producing *energy*. The next ones, producing **images, sounds and ideas**.",
    },
    cite: {
      ca: "— Catalunya Media City · Nau de Turbines",
      es: "— Catalunya Media City · Nave de Turbinas",
      en: "— Catalunya Media City · Turbine Hall",
    },
  },
  { kind: "figure", src: "assets/render-turbines-int-2.jpg", num: "04", ratio: "wide",
    desc: {
      ca: "Sales d'experiència contemporànies dins la carcassa original. Un diàleg entre patrimoni industrial i nova funció cultural.",
      es: "Salas de experiencia contemporáneas dentro de la carcasa original. Un diálogo entre patrimonio industrial y nueva función cultural.",
      en: "Contemporary experience rooms inside the original shell. A dialogue between industrial heritage and new cultural function.",
    },
    source: { ca: "Render Interior · Nau de Turbines", es: "Render Interior · Nave de Turbinas", en: "Interior render · Turbine Hall" },
  },
];

export const ARTICLE_MEMORIA = [
  { kind: "section", t: { ca: "Un lloc per recordar", es: "Un lugar para recordar", en: "A place to remember" } },
  { kind: "p", lead: true, t: {
    ca: "Dins el marc general del projecte es destinarà un **espai de memòria** dedicat a la història del lloc, lligada a la industrialització del Barcelonès Nord i a les reivindicacions ciutadanes.",
    es: "Dentro del marco general del proyecto se destinará un **espacio de memoria** dedicado a la historia del lugar, ligada a la industrialización del Barcelonès Nord y a las reivindicaciones ciudadanas.",
    en: "Within the project's overall framework, a **memory space** will be dedicated to the site's history, tied to the industrialization of Barcelonès Nord and to citizen mobilizations.",
  }},
  { kind: "p", t: {
    ca: "Un equipament que no només expliqui l'arquitectura — això ja ho fa l'edifici — sinó *les persones* que el van construir, fer funcionar i defensar.",
    es: "Un equipamiento que no solo explique la arquitectura — eso ya lo hace el edificio — sino *las personas* que lo construyeron, lo hicieron funcionar y lo defendieron.",
    en: "A facility that doesn't just explain architecture — the building already does that — but rather *the people* who built it, ran it, and defended it.",
  }},
  { kind: "figure", src: "assets/turbines-1988.jpg", num: "01", year: "1988", ratio: "wide",
    desc: {
      ca: "L'interior de la nau de turbines tal com es trobava en plena operació. Aquesta fou la realitat industrial del lloc durant quaranta anys.",
      es: "El interior de la nave de turbinas tal como se encontraba en plena operación. Esta fue la realidad industrial del lugar durante cuarenta años.",
      en: "The interior of the turbine hall in full operation. This was the site's industrial reality for forty years.",
    },
    source: { ca: "Fons Històric Endesa", es: "Fondo Histórico Endesa", en: "Endesa Historical Archive" },
  },
  { kind: "section", t: { ca: "Tres històries entrelligades", es: "Tres historias entrelazadas", en: "Three interwoven stories" } },
  { kind: "p", t: {
    ca: "La memòria del lloc es construeix sobre tres grans relats que convergeixen en la mateixa parcel·la:",
    es: "La memoria del lugar se construye sobre tres grandes relatos que convergen en la misma parcela:",
    en: "The site's memory is built on three major narratives that converge in the same plot:",
  }},
  { kind: "p", t: {
    ca: "**La indústria.** Cent anys de producció elèctrica que van alimentar el creixement industrial i urbà de Catalunya. Tecnologia, treball i un sistema energètic complex.",
    es: "**La industria.** Cien años de producción eléctrica que alimentaron el crecimiento industrial y urbano de Cataluña. Tecnología, trabajo y un sistema energético complejo.",
    en: "**The industry.** A hundred years of electrical production that fueled Catalonia's industrial and urban growth. Technology, labour and a complex energy system.",
  }},
  { kind: "p", t: {
    ca: "**El treball.** Milers de persones — moltes immigrades del sud peninsular — van treballar a la central. Les seves vides van configurar el barri.",
    es: "**El trabajo.** Miles de personas — muchas inmigradas del sur peninsular — trabajaron en la central. Sus vidas configuraron el barrio.",
    en: "**The labour.** Thousands of people — many migrants from southern Spain — worked at the plant. Their lives shaped the neighborhood.",
  }},
  { kind: "p", t: {
    ca: "**La reivindicació.** Mig segle de mobilització veïnal, des del «polsim negre» del 1966 fins al referèndum del 2008. Una pedagogia democràtica que va salvar les xemeneies.",
    es: "**La reivindicación.** Medio siglo de movilización vecinal, desde el «polvillo negro» de 1966 hasta el referéndum de 2008. Una pedagogía democrática que salvó las chimeneas.",
    en: "**The mobilization.** Half a century of neighborhood action, from the 1966 \u201Cblack soot\u201D to the 2008 referendum. A democratic pedagogy that saved the chimneys.",
  }},
  { kind: "figure", src: "assets/actual-aeria.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "Detalls actuals de l'estructura. Cada superfície conserva inscripcions, marques i traces que componen l'arxiu físic del lloc.",
      es: "Detalles actuales de la estructura. Cada superficie conserva inscripciones, marcas y trazas que componen el archivo físico del lugar.",
      en: "Current details of the structure. Every surface holds inscriptions, marks and traces that make up the site's physical archive.",
    },
    source: { ca: "Arxiu fotogràfic actual", es: "Archivo fotográfico actual", en: "Contemporary photo archive" },
  },
  { kind: "quote",
    t: {
      ca: "Conservar el formigó és **fàcil**. Conservar la *memòria* ho és menys.",
      es: "Conservar el hormigón es **fácil**. Conservar la *memoria* lo es menos.",
      en: "Preserving concrete is **easy**. Preserving *memory* is harder.",
    },
    cite: {
      ca: "— Espai de memòria · Tres Xemeneies",
      es: "— Espacio de memoria · Tres Chimeneas",
      en: "— Memory space · Three Chimneys",
    },
  },
  { kind: "section", t: { ca: "Funcions", es: "Funciones", en: "Functions" } },
  { kind: "p", t: {
    ca: "L'espai de memòria es pensa com un equipament obert que combinarà tres tipus d'activitat. **Exposició permanent** sobre la història industrial i social del recinte. **Programació temporal** amb projectes artístics, comissariats i recerca aplicada. I **arxiu obert**: testimonis orals, documents i materials accessibles al públic i als investigadors.",
    es: "El espacio de memoria se piensa como un equipamiento abierto que combinará tres tipos de actividad. **Exposición permanente** sobre la historia industrial y social del recinto. **Programación temporal** con proyectos artísticos, comisariados e investigación aplicada. Y **archivo abierto**: testimonios orales, documentos y materiales accesibles al público y a investigadores.",
    en: "The memory space is conceived as an open facility combining three kinds of activity. A **permanent exhibition** on the site's industrial and social history. A **temporary programme** with artistic projects, curatorial work and applied research. And an **open archive**: oral testimonies, documents and materials accessible to the public and researchers.",
  }},
  { kind: "figure", src: "assets/actual-05.jpg", num: "03", ratio: "tall",
    desc: {
      ca: "Una de les voltes de formigó. L'estructura mateixa esdevé el primer document de l'arxiu: cada marca és una traça del que va passar aquí.",
      es: "Una de las bóvedas de hormigón. La estructura misma se convierte en el primer documento del archivo: cada marca es una traza de lo que pasó aquí.",
      en: "One of the concrete vaults. The structure itself becomes the archive's first document: every mark is a trace of what happened here.",
    },
    source: { ca: "Arxiu fotogràfic actual", es: "Archivo fotográfico actual", en: "Contemporary photo archive" },
  },
  { kind: "section", t: { ca: "Una ciutat amb memòria", es: "Una ciudad con memoria", en: "A city with memory" } },
  { kind: "p", t: {
    ca: "La transformació del recinte de les Tres Xemeneies no és només una operació urbanística. És una **decisió cultural**: triar què recordem i com ho transmetem a les generacions que vindran.",
    es: "La transformación del recinto de las Tres Chimeneas no es solo una operación urbanística. Es una **decisión cultural**: elegir qué recordamos y cómo lo transmitimos a las generaciones que vendrán.",
    en: "Transforming the Three Chimneys site is not just an urban planning operation. It's a **cultural decision**: choosing what to remember and how to pass it on to coming generations.",
  }},
  { kind: "p", t: {
    ca: "La història del lloc no s'acaba aquí. *Comença una nova etapa.*",
    es: "La historia del lugar no acaba aquí. *Comienza una nueva etapa.*",
    en: "The site's story doesn't end here. *A new era begins.*",
  }},
];