// articles.jsx — Contingut complet dels 8 capítols
// Font: «PROPOSTA NOU TEXT» (Consorci del Besòs, 31.07.2026)
// Cada array és la seqüència de blocs que es renderitza via renderChapter(blocks, lang).

export const ARTICLE_ICONA = [
  { kind: "p", lead: true, t: {
    ca: "Les Tres Xemeneies no són només una fita en l'horitzó metropolità: són les **sentinelles de la memòria obrera** i el monument industrial més alt de la Mediterrània dins la seva tipologia.",
    es: "Las Tres Chimeneas no son sólo un hito en el horizonte metropolitano: son las **centinelas de la memoria obrera** y el monumento industrial más alto del Mediterráneo dentro de su tipología.",
    en: "The Three Chimneys are more than a landmark on the metropolitan skyline: they are the **sentinels of working-class memory** and the tallest industrial monument in the Mediterranean within their typology.",
  }},
  { kind: "p", t: {
    ca: "Amb els seus **200 metres d'alçada**, defineixen l'estètica del litoral entre Sant Adrià de Besòs i Badalona, i simbolitzen una transició imparable: del passat del carbó i el fueloil al futur de la innovació digital.",
    es: "Con sus **200 metros de altura**, definen la estética del litoral entre Sant Adrià de Besòs y Badalona, y simbolizan una transición imparable: del pasado del carbón y el fuelóleo al futuro de la innovación digital.",
    en: "At **200 metres tall**, they define the coastline between Sant Adrià de Besòs and Badalona, and stand for an unstoppable transition: from a past of coal and fuel oil to a future of digital innovation.",
  }},
  { kind: "figure", src: "/assets/fotografies/actual-aeria.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Vista aèria actual del conjunt de les Tres Xemeneies, a la desembocadura del Besòs, entre Sant Adrià i Badalona.",
      es: "Vista aérea actual del conjunto de las Tres Chimeneas, en la desembocadura del Besòs, entre Sant Adrià y Badalona.",
      en: "Present-day aerial view of the Three Chimneys complex at the mouth of the Besòs, between Sant Adrià and Badalona.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
  { kind: "section", t: { ca: "Un símbol d'identitat col·lectiva", es: "Un símbolo de identidad colectiva", en: "A symbol of collective identity" } },
  { kind: "p", t: {
    ca: "Aquest conjunt, declarat **Bé Cultural d'Interès Local (BCIL)**, ha passat de ser una infraestructura de generació elèctrica a convertir-se en un símbol d'identitat col·lectiva.",
    es: "Este conjunto, declarado **Bien Cultural de Interés Local (BCIL)**, ha pasado de ser una infraestructura de generación eléctrica a convertirse en un símbolo de identidad colectiva.",
    en: "Listed as a **Local Cultural Heritage Asset (BCIL)**, the complex has gone from being an electricity-generating facility to a symbol of collective identity.",
  }},
  { kind: "p", t: {
    ca: "Avui, les Tres Xemeneies s'alcen com el cor d'una transformació urbana de **32 hectàrees** que busca recosir el front marítim i situar Catalunya al centre de la indústria creativa mundial.",
    es: "Hoy, las Tres Chimeneas se alzan como el corazón de una transformación urbana de **32 hectáreas** que busca recoser el frente marítimo y situar a Cataluña en el centro de la industria creativa mundial.",
    en: "Today the Three Chimneys stand at the heart of a **32-hectare** urban transformation that aims to stitch the seafront back together and place Catalonia at the centre of the global creative industry.",
  }},
  { kind: "stats", head: { ca: "Dades ràpides", es: "Datos rápidos", en: "Quick facts" },
    items: [
      { num: "200", unit: "m",
        label: { ca: "Alçada", es: "Altura", en: "Height" },
        desc:  { ca: "L'estructura industrial més alta del litoral mediterrani.", es: "La estructura industrial más alta del litoral mediterráneo.", en: "The tallest industrial structure on the Mediterranean coast." } },
      { num: "32", unit: "ha",
        label: { ca: "Superfície del sector", es: "Superficie del sector", en: "Sector surface" },
        desc:  { ca: "En transformació integral.", es: "En transformación integral.", en: "Undergoing full transformation." } },
      { num: "2016",
        label: { ca: "Protecció patrimonial", es: "Protección patrimonial", en: "Heritage listing" },
        desc:  { ca: "Declarat Bé Cultural d'Interès Local.", es: "Declarado Bien Cultural de Interés Local.", en: "Listed as Local Cultural Heritage Asset." } },
      { num: "3",
        label: { ca: "Xemeneies", es: "Chimeneas", en: "Chimneys" },
        desc:  { ca: "En fase de reconversió cap al hub Catalunya Media City.", es: "En fase de reconversión hacia el hub Catalunya Media City.", en: "Being converted into the Catalunya Media City hub." } },
    ],
  },
  { kind: "figure", video: "/assets/videos/video-chimneys.mp4", poster: "/assets/fotografies/actual-01.jpg", num: "02", ratio: "tall",
    desc: {
      ca: "Les tres xemeneies de formigó, de 200 metres, vistes des de la base del conjunt.",
      es: "Las tres chimeneas de hormigón, de 200 metros, vistas desde la base del conjunto.",
      en: "The three 200-metre concrete chimneys seen from the base of the complex.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
  { kind: "quote",
    t: {
      ca: "De motor industrial a **far de la creativitat digital**.",
      es: "De motor industrial a **faro de la creatividad digital**.",
      en: "From industrial engine to **beacon of digital creativity**.",
    },
    cite: {
      ca: "— Les Tres Xemeneies · 1913 — 2025",
      es: "— Las Tres Chimeneas · 1913 — 2025",
      en: "— The Three Chimneys · 1913 — 2025",
    },
  },
];

export const ARTICLE_ORIGENS = [
  { kind: "section", t: { ca: "El bressol de l'energia", es: "La cuna de la energía", en: "The cradle of energy" } },
  { kind: "p", lead: true, t: {
    ca: "La gènesi elèctrica a la desembocadura del Besòs data de **1913**, quan l'empresa *Energía Eléctrica de Cataluña* va inaugurar la primera central tèrmica de carbó per alimentar una Barcelona en plena ebullició industrial.",
    es: "La génesis eléctrica en la desembocadura del Besòs data de **1913**, cuando la empresa *Energía Eléctrica de Cataluña* inauguró la primera central térmica de carbón para alimentar a una Barcelona en plena ebullición industrial.",
    en: "The electrical genesis at the mouth of the Besòs dates to **1913**, when *Energía Eléctrica de Cataluña* opened the first coal-fired thermal plant to power a Barcelona in full industrial boil.",
  }},
  { kind: "p", t: {
    ca: "El projecte, signat per l'arquitecte **Eduard Ferrés**, va ser una fita d'enginyeria en utilitzar per primer cop a Catalunya el sistema **Hennebique** de formigó armat per a una estructura d'aquestes dimensions.",
    es: "El proyecto, firmado por el arquitecto **Eduard Ferrés**, fue un hito de ingeniería al utilizar por primera vez en Cataluña el sistema **Hennebique** de hormigón armado para una estructura de estas dimensiones.",
    en: "The project, signed by architect **Eduard Ferrés**, was an engineering milestone: the first use in Catalonia of the **Hennebique** reinforced-concrete system on a structure of this scale.",
  }},
  { kind: "figure", src: "/assets/fotografies/construccio-1971.jpg", num: "01", year: "c.1925", ratio: "wide",
    desc: {
      ca: "Primera central tèrmica del Besòs. Vista aèria amb les quatre xemeneies de maons originals, els horts circumdants i el moll de descàrrega de carbó que s'endinsava al mar.",
      es: "Primera central térmica del Besòs. Vista aérea con las cuatro chimeneas de ladrillo originales, las huertas circundantes y el muelle de descarga de carbón adentrándose en el mar.",
      en: "The first Besòs thermal plant. Aerial view of the four original brick chimneys, surrounding orchards, and the coal-unloading pier reaching into the sea.",
    },
    source: { ca: "Arxiu Nacional de Catalunya · Fons FECSA-Endesa", es: "Archivo Nacional de Cataluña · Fondo FECSA-Endesa", en: "National Archive of Catalonia · FECSA-Endesa collection" },
  },
  { kind: "section", t: { ca: "Tecnologia pionera", es: "Tecnología pionera", en: "Pioneering technology" } },
  { kind: "p", t: {
    ca: "Aquesta planta no només era innovadora per la seva arquitectura, sinó també per la seva infraestructura tècnica. Per a la condensació del vapor s'utilitzava **aigua de mar** captada mitjançant unes imponents estructures que s'endinsaven **150 metres** dins la Mediterrània.",
    es: "Esta planta no sólo era innovadora por su arquitectura, sino también por su infraestructura técnica. Para la condensación del vapor se utilizaba **agua de mar** captada mediante unas imponentes estructuras que se adentraban **150 metros** en el Mediterráneo.",
    en: "The plant was innovative not only architecturally but technically. Steam was condensed using **seawater** drawn in through imposing structures that reached **150 metres** into the Mediterranean.",
  }},
  { kind: "p", t: {
    ca: "Les obres van començar l'abril de 1912 i la central es va connectar a la xarxa el **23 de març de 1913**. El projecte preveia vuit turboalternadors; en l'engegada només n'entraren en funcionament dos, de 7,5 MW cadascun. Un any més tard s'ampliava amb un grup de 15 MW.",
    es: "Las obras comenzaron en abril de 1912 y la central se conectó a la red el **23 de marzo de 1913**. El proyecto preveía ocho turboalternadores; en la puesta en marcha sólo entraron en funcionamiento dos, de 7,5 MW cada uno. Un año después se ampliaba con un grupo de 15 MW.",
    en: "Construction began in April 1912 and the plant was connected to the grid on **23 March 1913**. The original project foresaw eight turbo-alternators; only two went into operation initially, at 7.5 MW each. A year later a 15 MW group was added.",
  }},
  { kind: "stats", head: { ca: "La primera central · 1913", es: "La primera central · 1913", en: "The first plant · 1913" },
    items: [
      { num: "30", unit: "MW",
        label: { ca: "Potència total",     es: "Potencia total",     en: "Total power" },
        desc:  { ca: "2 grups de 7,5 + 1 de 15.", es: "2 grupos de 7,5 + 1 de 15.", en: "Two 7.5 MW groups + one 15 MW." } },
      { num: "4",
        label: { ca: "Xemeneies de maons", es: "Chimeneas de ladrillo", en: "Brick chimneys" },
        desc:  { ca: "60 m d'alçada cadascuna.", es: "60 m de altura cada una.", en: "60 m tall each." } },
      { num: "16",
        label: { ca: "Generadors de vapor", es: "Generadores de vapor", en: "Steam generators" },
        desc:  { ca: "Sistema Delaunay-Belleville.", es: "Sistema Delaunay-Belleville.", en: "Delaunay-Belleville system." } },
      { num: "150", unit: "m",
        label: { ca: "Captació al mar", es: "Captación marina", en: "Sea intake" },
        desc:  { ca: "Estructures per al refredament.", es: "Estructuras para la refrigeración.", en: "Structures for cooling." } },
    ],
  },
  { kind: "section", t: { ca: "La primera xarxa d'alta tensió", es: "La primera red de alta tensión", en: "The first high-voltage grid" } },
  { kind: "p", t: {
    ca: "La central formava part de la **primera xarxa d'alta tensió del país**, connectant-se amb la planta hidroelèctrica de *Cabdella* (Pirineus) a través d'una línia de **80 kV i 175 km** de longitud. Això va convertir el Besòs en peça clau del sistema elèctric català.",
    es: "La central formaba parte de la **primera red de alta tensión del país**, conectándose con la planta hidroeléctrica de *Cabdella* (Pirineos) a través de una línea de **80 kV y 175 km** de longitud. Esto convirtió al Besòs en pieza clave del sistema eléctrico catalán.",
    en: "The plant formed part of the **country's first high-voltage grid**, linked to the *Cabdella* hydroelectric station in the Pyrenees by an **80 kV, 175 km** line. This made the Besòs a keystone of the Catalan electrical system.",
  }},
  { kind: "quote",
    t: {
      ca: "La primera xarxa d'alta tensió de **175 quilòmetres** que va connectar *el Pirineu amb el mar*.",
      es: "La primera red de alta tensión de **175 kilómetros** que conectó *el Pirineo con el mar*.",
      en: "The first high-voltage grid of **175 kilometres** to connect *the Pyrenees with the sea*.",
    },
    cite: {
      ca: "— Línia Cabdella–Besòs · 80 kV · 1913",
      es: "— Línea Cabdella–Besòs · 80 kV · 1913",
      en: "— Cabdella–Besòs line · 80 kV · 1913",
    },
  },
  { kind: "figure", src: "/assets/fotografies/turbines-1988.jpg", num: "02", year: "c.1925", ratio: "wide",
    desc: {
      ca: "Interior de la sala de turbines. Setze generadors Delaunay-Belleville produïen el vapor a partir de la combustió de carbó britànic.",
      es: "Interior de la sala de turbinas. Dieciséis generadores Delaunay-Belleville producían el vapor a partir de la combustión de carbón británico.",
      en: "Inside the turbine hall. Sixteen Delaunay-Belleville generators produced steam from British coal combustion.",
    },
    source: { ca: "Arxiu Nacional de Catalunya · Fons FECSA-Endesa", es: "Archivo Nacional de Cataluña · Fondo FECSA-Endesa", en: "National Archive of Catalonia · FECSA-Endesa collection" },
  },
  { kind: "list", head: { ca: "Cronologia fundacional", es: "Cronología fundacional", en: "Founding chronology" },
    items: [
      { k: "1912", t: {
        ca: "Comencen les obres, sobre projecte d'Eduard Ferrés, amb el sistema Hennebique de formigó armat.",
        es: "Comienzan las obras, sobre proyecto de Eduard Ferrés, con el sistema Hennebique de hormigón armado.",
        en: "Construction starts, to Eduard Ferrés's design, using the Hennebique reinforced-concrete system.",
      }},
      { k: "1913", t: {
        ca: "Inauguració i connexió a la xarxa el **23 de març**.",
        es: "Inauguración y conexión a la red el **23 de marzo**.",
        en: "Inauguration and grid connection on **23 March**.",
      }},
      { k: "1923", t: {
        ca: "L'empresa passa a mans de la **Barcelona Traction** (*la Canadenca*), recuperant la producció després de la crisi de la Primera Guerra Mundial.",
        es: "La empresa pasa a manos de la **Barcelona Traction** (*la Canadiense*), recuperando la producción tras la crisis de la Primera Guerra Mundial.",
        en: "The company passes to **Barcelona Traction** (*the Canadian*), recovering production after the First World War crisis.",
      }},
    ],
  },
  { kind: "figure", src: "/assets/fotografies/aerea-1913.jpg", num: "03", year: "1912", ratio: "wide",
    desc: {
      ca: "Arc d'entrada de la central original, amb la inscripció **1912** gravada en la pedra.",
      es: "Arco de entrada de la central original, con la inscripción **1912** grabada en la piedra.",
      en: "Entrance arch of the original plant, with **1912** carved into the stone.",
    },
    source: { ca: "Arxiu Nacional de Catalunya · Fons FECSA-Endesa", es: "Archivo Nacional de Cataluña · Fondo FECSA-Endesa", en: "National Archive of Catalonia · FECSA-Endesa collection" },
  },
];

export const ARTICLE_GUERRES = [
  { kind: "section", t: { ca: "El bloqueig del carbó", es: "El bloqueo del carbón", en: "The coal blockade" } },
  { kind: "p", lead: true, t: {
    ca: "L'activitat de la central es va veure seriosament afectada durant la **Primera Guerra Mundial** pel bloqueig marítim que dificultava l'abastament del carbó que arribava de la Gran Bretanya. A partir del **1923** es va recuperar la producció.",
    es: "La actividad de la central se vio seriamente afectada durante la **Primera Guerra Mundial** por el bloqueo marítimo que dificultaba el abastecimiento del carbón que llegaba de Gran Bretaña. A partir de **1923** se recuperó la producción.",
    en: "The plant's activity was seriously affected during the **First World War** by the maritime blockade that disrupted the supply of coal arriving from Great Britain. From **1923** production recovered.",
  }},
  { kind: "p", t: {
    ca: "De manera que durant la **Guerra Civil espanyola (1936-39)** va esdevenir una central estratègica, perquè garantia el subministrament elèctric de Barcelona. Per aquest motiu va esdevenir un **objectiu militar crític**.",
    es: "De manera que durante la **Guerra Civil española (1936-39)** se convirtió en una central estratégica, porque garantizaba el suministro eléctrico de Barcelona. Por este motivo se convirtió en un **objetivo militar crítico**.",
    en: "So during the **Spanish Civil War (1936-39)** it became a strategic plant, because it guaranteed Barcelona's electricity supply. For that reason it became a **critical military target**.",
  }},
  { kind: "figure", src: "/assets/fotografies/construccio-1971-b.jpg", num: "01", year: "c.1930", ratio: "wide",
    desc: {
      ca: "La central del Besòs als anys trenta, quan garantia el subministrament elèctric de Barcelona.",
      es: "La central del Besòs en los años treinta, cuando garantizaba el suministro eléctrico de Barcelona.",
      en: "The Besòs plant in the 1930s, when it guaranteed Barcelona's electricity supply.",
    },
    source: { ca: "Arxiu Nacional de Catalunya · Fons FECSA-Endesa", es: "Archivo Nacional de Cataluña · Fondo FECSA-Endesa", en: "National Archive of Catalonia · FECSA-Endesa collection" },
  },
  { kind: "section", t: { ca: "Un objectiu militar", es: "Un objetivo militar", en: "A military target" } },
  { kind: "p", t: {
    ca: "En un context de *guerra total*, l'**Aviazione Legionaria** italiana, aliada de Franco, va bombardejar sistemàticament el **Pla de Besòs** — nom de Sant Adrià en l'època — per colpejar el subministrament elèctric de Barcelona i desmoralitzar la rereguarda.",
    es: "En un contexto de *guerra total*, la **Aviazione Legionaria** italiana, aliada de Franco, bombardeó sistemáticamente el **Pla de Besòs** — nombre de Sant Adrià en la época — para golpear el suministro eléctrico de Barcelona y desmoralizar la retaguardia.",
    en: "In a context of *total war*, Italy's **Aviazione Legionaria**, allied with Franco, systematically bombed the **Pla de Besòs** — Sant Adrià's name at the time — to strike Barcelona's electricity supply and demoralize the home front.",
  }},
  { kind: "p", t: {
    ca: "L'atac més devastador va tenir lloc el **13 de novembre de 1938**, quan un bombardeig directe contra la central va causar **16 víctimes mortals**. Segons els registres històrics, la central mai es va recuperar totalment dels danys derivats d'aquell atac, marcant el principi de la seva obsolescència.",
    es: "El ataque más devastador tuvo lugar el **13 de noviembre de 1938**, cuando un bombardeo directo contra la central causó **16 víctimas mortales**. Según los registros históricos, la central nunca se recuperó totalmente de los daños derivados de aquel ataque, marcando el principio de su obsolescencia.",
    en: "The most devastating attack came on **13 November 1938**, when a direct bombing of the plant killed **16 people**. According to the historical record, the plant never fully recovered from that damage — the beginning of its obsolescence.",
  }},
  { kind: "fact", t: {
    ca: "L'aviació italiana va bombardejar la central el 13 de novembre de 1938, causant setze morts. **Mai es va recuperar dels danys.**",
    es: "La aviación italiana bombardeó la central el 13 de noviembre de 1938, causando dieciséis muertos. **Nunca se repuso de los daños.**",
    en: "Italian aviation bombed the plant on 13 November 1938, killing sixteen. **It never recovered from the damage.**",
  }},
  { kind: "section", t: { ca: "Espai de memòria: el refugi de la placeta Macià", es: "Espacio de memoria: el refugio de la placeta Macià", en: "Memory space: the placeta Macià shelter" } },
  { kind: "p", t: {
    ca: "Per protegir la població civil dels atacs — que van causar un total de **39 morts** al municipi — es van construir refugis com el de la **placeta Macià**, a Sant Adrià de Besòs. Avui aquest espai s'ha recuperat com a centre d'interpretació per mantenir viva la memòria d'aquells anys sota les bombes.",
    es: "Para proteger a la población civil de los ataques — que causaron un total de **39 muertos** en el municipio — se construyeron refugios como el de la **placeta Macià**, en Sant Adrià de Besòs. Hoy este espacio se ha recuperado como centro de interpretación para mantener viva la memoria de aquellos años bajo las bombas.",
    en: "To protect civilians from the raids — which killed **39 people** in the municipality — shelters were built, among them the one at **placeta Macià** in Sant Adrià de Besòs. Today it has been restored as an interpretation centre keeping alive the memory of those years under the bombs.",
  }},
  { kind: "p", t: {
    ca: "També el **1939**, durant la retirada republicana, es va volar part de la primera central tèrmica; només quedà operatiu un grup de 7,5 MW.",
    es: "También en **1939**, durante la retirada republicana, se voló parte de la primera central térmica; sólo quedó operativo un grupo de 7,5 MW.",
    en: "Also in **1939**, during the Republican retreat, part of the first thermal plant was blown up; only a 7.5 MW group remained operational.",
  }},
  { kind: "section", t: { ca: "Postguerra", es: "Posguerra", en: "The postwar years" } },
  { kind: "p", t: {
    ca: "Després de la guerra, la central tèrmica va seguir funcionant de manera limitada, fins que el **1948** l'empresa Barcelona Traction — *la Canadenca* — va veure els seus actius integrats a la nounada **Fuerzas Eléctricas de Cataluña, S.A. (FECSA)**, que s'acabava de crear.",
    es: "Después de la guerra, la central térmica siguió funcionando de manera limitada, hasta que en **1948** la empresa Barcelona Traction — *la Canadiense* — vio sus activos integrados en la recién nacida **Fuerzas Eléctricas de Cataluña, S.A. (FECSA)**, que acababa de crearse.",
    en: "After the war the plant kept running on a limited basis, until in **1948** Barcelona Traction — *the Canadian* — saw its assets folded into the newly created **Fuerzas Eléctricas de Cataluña, S.A. (FECSA)**.",
  }},
  { kind: "p", t: {
    ca: "Uns anys més tard, el **1954**, FECSA va aturar la seva activitat: el tancament de la primera central, obrint pas a les estructures modernes que avui coneixem.",
    es: "Unos años más tarde, en **1954**, FECSA detuvo su actividad: el cierre de la primera central, abriendo paso a las estructuras modernas que hoy conocemos.",
    en: "A few years later, in **1954**, FECSA shut it down: the closure of the first plant, clearing the way for the modern structures we know today.",
  }},
  { kind: "list", head: { ca: "De la guerra al tancament", es: "De la guerra al cierre", en: "From war to closure" },
    items: [
      { k: "1936–39", t: {
        ca: "Central estratègica per al subministrament de Barcelona i, per tant, objectiu militar.",
        es: "Central estratégica para el suministro de Barcelona y, por tanto, objetivo militar.",
        en: "A strategic plant for Barcelona's supply — and therefore a military target.",
      }},
      { k: "13.11.1938", t: {
        ca: "Bombardeig directe de l'Aviazione Legionaria: **16 víctimes mortals**.",
        es: "Bombardeo directo de la Aviazione Legionaria: **16 víctimas mortales**.",
        en: "Direct bombing by the Aviazione Legionaria: **16 deaths**.",
      }},
      { k: "1939", t: {
        ca: "La retirada republicana vola part de la primera central tèrmica.",
        es: "La retirada republicana vuela parte de la primera central térmica.",
        en: "The Republican retreat blows up part of the first thermal plant.",
      }},
      { k: "1948", t: {
        ca: "Els actius de Barcelona Traction s'integren a la nova **FECSA**.",
        es: "Los activos de Barcelona Traction se integran en la nueva **FECSA**.",
        en: "Barcelona Traction's assets are folded into the new **FECSA**.",
      }},
      { k: "1954", t: {
        ca: "Tancament definitiu de la primera central del Besòs.",
        es: "Cierre definitivo de la primera central del Besòs.",
        en: "Definitive closure of the first Besòs plant.",
      }},
    ],
  },
];

export const ARTICLE_BRUTALISME = [
  { kind: "section", t: { ca: "Demanda creixent", es: "Demanda creciente", en: "Growing demand" } },
  { kind: "p", lead: true, t: {
    ca: "El desenvolupament industrial i l'augment de la població van provocar el creixement accelerat de la demanda d'energia elèctrica a l'àrea metropolitana de Barcelona. **FECSA** va decidir invertir en noves instal·lacions termoelèctriques que reforcessin la producció de la regió.",
    es: "El desarrollo industrial y el aumento de la población provocaron el crecimiento acelerado de la demanda de energía eléctrica en el área metropolitana de Barcelona. **FECSA** decidió invertir en nuevas instalaciones termoeléctricas que reforzaran la producción de la región.",
    en: "Industrial growth and a rising population drove a sharp increase in electricity demand across metropolitan Barcelona. **FECSA** decided to invest in new thermoelectric facilities to reinforce the region's output.",
  }},
  { kind: "p", t: {
    ca: "Entre **1959 i 1965** es van posar en marxa les noves instal·lacions: les plantes **Badalona I** (1959) i **Badalona II** (1965) van suposar un salt energètic a la comarca, a la vegada que van generar controvèrsia per l'augment de la contaminació atmosfèrica que provocaven.",
    es: "Entre **1959 y 1965** se pusieron en marcha las nuevas instalaciones: las plantas **Badalona I** (1959) y **Badalona II** (1965) supusieron un salto energético en la comarca, a la vez que generaron controversia por el aumento de la contaminación atmosférica que provocaban.",
    en: "Between **1959 and 1965** the new facilities came online: **Badalona I** (1959) and **Badalona II** (1965) marked an energy leap for the area, while stirring controversy over the air pollution they caused.",
  }},
  { kind: "figure", src: "/assets/fotografies/construccio-1971.jpg", num: "01", year: "1971", ratio: "wide",
    desc: {
      ca: "Obres de construcció del nou conjunt brutalista, iniciades el 1971.",
      es: "Obras de construcción del nuevo conjunto brutalista, iniciadas en 1971.",
      en: "Construction of the new brutalist complex, begun in 1971.",
    },
    source: { ca: "Arxiu Nacional de Catalunya · Fons FECSA-Endesa", es: "Archivo Nacional de Cataluña · Fondo FECSA-Endesa", en: "National Archive of Catalonia · FECSA-Endesa collection" },
  },
  { kind: "section", t: { ca: "Mil cinquanta megawatts", es: "Mil cincuenta megavatios", en: "1,050 megawatts" } },
  { kind: "p", t: {
    ca: "L'actual silueta de les Tres Xemeneies respon al creixement accelerat de la demanda energètica dels anys seixanta i setanta. Construïda entre **1971 i 1976** sota un estricte **estil brutalista**, la planta va assolir una potència de **1.050 MW**, una capacitat comparable a la producció d'una central nuclear convencional.",
    es: "La actual silueta de las Tres Chimeneas responde al crecimiento acelerado de la demanda energética de los años sesenta y setenta. Construida entre **1971 y 1976** bajo un estricto **estilo brutalista**, la planta alcanzó una potencia de **1.050 MW**, una capacidad comparable a la producción de una central nuclear convencional.",
    en: "The silhouette we know today answers the surging energy demand of the 1960s and 70s. Built between **1971 and 1976** in a strict **brutalist style**, the plant reached **1,050 MW** — a capacity comparable to a conventional nuclear station.",
  }},
  { kind: "stats", head: { ca: "La central brutalista", es: "La central brutalista", en: "The brutalist plant" },
    items: [
      { num: "1.050", unit: "MW",
        label: { ca: "Potència", es: "Potencia", en: "Power" },
        desc:  { ca: "Comparable a una central nuclear.", es: "Comparable a una central nuclear.", en: "Comparable to a nuclear station." } },
      { num: "200", unit: "m",
        label: { ca: "Alçada final", es: "Altura final", en: "Final height" },
        desc:  { ca: "Elevada des dels 180 m del projecte original.", es: "Elevada desde los 180 m del proyecto original.", en: "Raised from the original project's 180 m." } },
      { num: "57.000", unit: "t",
        label: { ca: "SO₂ a l'any", es: "SO₂ al año", en: "SO₂ per year" },
        desc:  { ca: "Emissions de diòxid de sofre.", es: "Emisiones de dióxido de azufre.", en: "Sulphur dioxide emissions." } },
      { num: "1983",
        label: { ca: "Zona contaminada", es: "Zona contaminada", en: "Polluted zone" },
        desc:  { ca: "Sant Adrià, declarada zona atmosfèrica contaminada.", es: "Sant Adrià, declarada zona atmosférica contaminada.", en: "Sant Adrià declared an atmospherically polluted zone." } },
    ],
  },
  { kind: "section", t: { ca: "El polsim negre", es: "El polvillo negro", en: "The black soot" } },
  { kind: "p", t: {
    ca: "Aquesta potència, però, tenia un preu ambiental altíssim: la central arribava a emetre **57.000 tones de diòxid de sofre (SO₂) a l'any**. L'ús de combustibles com el *cop de petroli* — un residu pesat i extremadament brut — va generar el famós **polsim negre** que va marcar la vida dels veïns.",
    es: "Esta potencia, sin embargo, tenía un precio ambiental altísimo: la central llegaba a emitir **57.000 toneladas de dióxido de azufre (SO₂) al año**. El uso de combustibles como el *coque de petróleo* — un residuo pesado y extremadamente sucio — generó el famoso **polvillo negro** que marcó la vida de los vecinos.",
    en: "That power came at a very high environmental price: the plant emitted up to **57,000 tonnes of sulphur dioxide (SO₂) a year**. Fuels such as *petroleum coke* — a heavy, extremely dirty residue — produced the notorious **black soot** that shaped residents' lives.",
  }},
  { kind: "figure", src: "/assets/fotografies/actual-03.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "Les tres xemeneies asimètriques: 53 metres de separació entre la primera i la segona, 63 entre la segona i la tercera.",
      es: "Las tres chimeneas asimétricas: 53 metros de separación entre la primera y la segunda, 63 entre la segunda y la tercera.",
      en: "The three asymmetrical chimneys: 53 metres between the first and second, 63 between the second and third.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
  { kind: "list", head: { ca: "Enginyeria i context social", es: "Ingeniería y contexto social", en: "Engineering and social context" },
    items: [
      { k: { ca: "Asimetria tècnica", es: "Asimetría técnica", en: "Technical asymmetry" }, t: {
        ca: "Les xemeneies no són equidistants — **53 m i 63 m** de separació — perquè la tercera turbina no estava prevista inicialment i es va haver d'adaptar al terreny vora el riu.",
        es: "Las chimeneas no son equidistantes — **53 m y 63 m** de separación — porque la tercera turbina no estaba prevista inicialmente y hubo que adaptarla al terreno junto al río.",
        en: "The chimneys are not equidistant — **53 m and 63 m** apart — because the third turbine was not initially planned and had to be fitted to the riverside terrain.",
      }},
      { k: { ca: "Força del treball", es: "Fuerza del trabajo", en: "The workforce" }, t: {
        ca: "La construcció i operació de la planta va ser possible gràcies a l'esforç de **milers de treballadors**, molts d'ells immigrants procedents del sud d'Espanya que van trobar en la central la seva porta d'entrada al desenvolupament metropolità.",
        es: "La construcción y operación de la planta fue posible gracias al esfuerzo de **miles de trabajadores**, muchos de ellos inmigrantes procedentes del sur de España que encontraron en la central su puerta de entrada al desarrollo metropolitano.",
        en: "Building and running the plant was possible thanks to **thousands of workers**, many of them migrants from southern Spain for whom the plant was their entry point into metropolitan development.",
      }},
      { k: { ca: "La revolta de les dones · 1966", es: "La revuelta de las mujeres · 1966", en: "The women's revolt · 1966" }, t: {
        ca: "**Més de mil veïnes** van protagonitzar protestes històriques contra la contaminació. La seva pressió davant el Ministeri va obligar a elevar l'alçada de les xemeneies del projecte original: **de 180 m a 200 m** per dispersar millor els gasos.",
        es: "**Más de mil vecinas** protagonizaron protestas históricas contra la contaminación. Su presión ante el Ministerio obligó a elevar la altura de las chimeneas del proyecto original: **de 180 m a 200 m** para dispersar mejor los gases.",
        en: "**More than a thousand women** led historic protests against the pollution. Their pressure on the Ministry forced the chimneys to be raised from the original design's **180 m to 200 m** to disperse the gases better.",
      }},
      { k: { ca: "Conflictes ambientals", es: "Conflictos ambientales", en: "Environmental conflicts" }, t: {
        ca: "La central va ser una font constant de conflictes: alteracions de la fauna marina per l'abocament d'aigua calenta i una incidència de **malalties respiratòries superior a la mitjana catalana**. Com a conseqüència, el **1983** es va decretar oficialment Sant Adrià de Besòs com a *zona atmosfèrica contaminada*.",
        es: "La central fue una fuente constante de conflictos: alteraciones de la fauna marina por el vertido de agua caliente y una incidencia de **enfermedades respiratorias superior a la media catalana**. Como consecuencia, en **1983** se decretó oficialmente Sant Adrià de Besòs como *zona atmosférica contaminada*.",
        en: "The plant was a constant source of conflict: disruption of marine life from hot-water discharge and a rate of **respiratory illness above the Catalan average**. As a result, in **1983** Sant Adrià de Besòs was officially declared an *atmospherically polluted zone*.",
      }},
    ],
  },
  { kind: "quote",
    t: {
      ca: "Més de mil dones van aconseguir el que cap informe tècnic no havia aconseguit: **vint metres més de xemeneia**.",
      es: "Más de mil mujeres consiguieron lo que ningún informe técnico había logrado: **veinte metros más de chimenea**.",
      en: "More than a thousand women achieved what no technical report had: **twenty more metres of chimney**.",
    },
    cite: {
      ca: "— La revolta de les dones · 1966",
      es: "— La revuelta de las mujeres · 1966",
      en: "— The women's revolt · 1966",
    },
  },
  { kind: "figure", src: "/assets/fotografies/actual-04.jpg", num: "03", ratio: "wide",
    desc: {
      ca: "Estructura de formigó de la nau de turbines, exemple del llenguatge brutalista de la central.",
      es: "Estructura de hormigón de la nave de turbinas, ejemplo del lenguaje brutalista de la central.",
      en: "Concrete structure of the turbine hall, an example of the plant's brutalist language.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
];

export const ARTICLE_LLUITA = [
  { kind: "section", t: { ca: "Un monument a la dignitat laboral", es: "Un monumento a la dignidad laboral", en: "A monument to labour dignity" } },
  { kind: "p", lead: true, t: {
    ca: "Les Tres Xemeneies són també un monument a la dignitat laboral. El **3 d'abril de 1973**, durant la construcció del primer bloc, la repressió policial contra una protesta obrera per millores laborals va segar la vida del treballador **Manuel Fernández Márquez**, de 27 anys.",
    es: "Las Tres Chimeneas son también un monumento a la dignidad laboral. El **3 de abril de 1973**, durante la construcción del primer bloque, la represión policial contra una protesta obrera por mejoras laborales segó la vida del trabajador **Manuel Fernández Márquez**, de 27 años.",
    en: "The Three Chimneys are also a monument to labour dignity. On **3 April 1973**, during construction of the first block, police repression of a workers' protest over pay and conditions took the life of **Manuel Fernández Márquez**, aged 27.",
  }},
  { kind: "p", t: {
    ca: "Un fet que roman gravat en la identitat sindical de Sant Adrià i Badalona.",
    es: "Un hecho que permanece grabado en la identidad sindical de Sant Adrià y Badalona.",
    en: "An event that remains engraved in the trade-union identity of Sant Adrià and Badalona.",
  }},
  { kind: "fact", t: {
    ca: "3 d'abril de 1973. Manuel Fernández Márquez, 27 anys, mor per la repressió policial d'una protesta obrera a l'obra de la central. **La seva memòria és inseparable del conjunt.**",
    es: "3 de abril de 1973. Manuel Fernández Márquez, 27 años, muere por la represión policial de una protesta obrera en la obra de la central. **Su memoria es inseparable del conjunto.**",
    en: "3 April 1973. Manuel Fernández Márquez, 27, dies from police repression of a workers' protest at the plant's construction site. **His memory is inseparable from the site.**",
  }},
  { kind: "figure", src: "/assets/fotografies/actual-05.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "El conjunt de la central, escenari de dècades de conflicte laboral i mobilització veïnal.",
      es: "El conjunto de la central, escenario de décadas de conflicto laboral y movilización vecinal.",
      en: "The plant complex, the setting for decades of labour conflict and neighbourhood mobilization.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
  { kind: "section", t: { ca: "El camí cap a la conservació", es: "El camino hacia la conservación", en: "The road to conservation" } },
  { kind: "p", t: {
    ca: "Amb el tancament de l'activitat el **2011** per obsolescència, es va obrir el debat sobre el seu enderroc. Tanmateix, el sentiment de **propietat ciutadana** forjat durant dècades de convivència amb el gegant industrial es va imposar.",
    es: "Con el cierre de la actividad en **2011** por obsolescencia, se abrió el debate sobre su derribo. Sin embargo, el sentimiento de **propiedad ciudadana** forjado durante décadas de convivencia con el gigante industrial se impuso.",
    en: "When operations ended in **2011** through obsolescence, debate opened over demolition. But the sense of **civic ownership** forged over decades of living alongside the industrial giant prevailed.",
  }},
  { kind: "list", head: { ca: "La decisió ciutadana", es: "La decisión ciudadana", en: "The citizens' decision" },
    items: [
      { k: "2008", t: {
        ca: "En un **referèndum històric**, el **82 %** de la ciutadania va votar a favor de la conservació.",
        es: "En un **referéndum histórico**, el **82 %** de la ciudadanía votó a favor de la conservación.",
        en: "In a **historic referendum**, **82 %** of citizens voted in favour of conservation.",
      }},
      { k: "2011", t: {
        ca: "Endesa atura definitivament l'activitat de la central per obsolescència.",
        es: "Endesa detiene definitivamente la actividad de la central por obsolescencia.",
        en: "Endesa definitively halts the plant's activity through obsolescence.",
      }},
      { k: "2016", t: {
        ca: "La declaració com a **Bé Cultural d'Interès Local (BCIL)** aconsegueix protegir el seu valor com a patrimoni industrial.",
        es: "La declaración como **Bien Cultural de Interés Local (BCIL)** consigue proteger su valor como patrimonio industrial.",
        en: "Listing as a **Local Cultural Heritage Asset (BCIL)** secures protection of its industrial-heritage value.",
      }},
    ],
  },
  { kind: "quote",
    t: {
      ca: "El **82 %** de la ciutadania va votar per conservar-les. *No era només formigó: era la seva història.*",
      es: "El **82 %** de la ciudadanía votó por conservarlas. *No era sólo hormigón: era su historia.*",
      en: "**82 %** of citizens voted to keep them. *It was not just concrete: it was their history.*",
    },
    cite: {
      ca: "— Referèndum de conservació · 2008",
      es: "— Referéndum de conservación · 2008",
      en: "— Conservation referendum · 2008",
    },
  },
  { kind: "figure", src: "/assets/fotografies/actual-06.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "Les xemeneies conservades després del referèndum del 2008 i la declaració com a BCIL el 2016.",
      es: "Las chimeneas conservadas tras el referéndum de 2008 y la declaración como BCIL en 2016.",
      en: "The chimneys preserved after the 2008 referendum and the 2016 BCIL listing.",
    },
    source: { ca: "Arxiu Consorci del Besòs", es: "Archivo Consorci del Besòs", en: "Consorci del Besòs Archive" },
  },
];

export const ARTICLE_PDU = [
  { kind: "section", t: { ca: "Un nou model de ciutat", es: "Un nuevo modelo de ciudad", en: "A new model of city" } },
  { kind: "p", lead: true, t: {
    ca: "Aprovat el **2023**, el **Pla Director Urbanístic (PDU)** transforma aquest espai degradat en un nou pol de centralitat metropolitana basat en la **resiliència climàtica** i la barreja d'usos.",
    es: "Aprobado en **2023**, el **Plan Director Urbanístico (PDU)** transforma este espacio degradado en un nuevo polo de centralidad metropolitana basado en la **resiliencia climática** y la mezcla de usos.",
    en: "Approved in **2023**, the **Urban Master Plan (PDU)** turns this degraded area into a new metropolitan centrality based on **climate resilience** and mixed uses.",
  }},
  { kind: "p", t: {
    ca: "El PDU designa el **Consorci del Besòs** com a administració actuant i preveu la transformació d'unes **32 hectàrees** que inclouran el hub audiovisual, un gran **parc urbà de 10 ha**, més de **185.000 m² d'habitatge** — el 40 %, protegit — i uns **100.000 m² de sostre d'activitat econòmica**.",
    es: "El PDU designa el **Consorci del Besòs** como administración actuante y prevé la transformación de unas **32 hectáreas** que incluirán el hub audiovisual, un gran **parque urbano de 10 ha**, más de **185.000 m² de vivienda** — el 40 %, protegida — y unos **100.000 m² de techo de actividad económica**.",
    en: "The PDU names the **Consorci del Besòs** as acting authority and plans the transformation of some **32 hectares**, including the audiovisual hub, a large **10-ha urban park**, over **185,000 m² of housing** — 40 % of it protected — and around **100,000 m² of economic activity floorspace**.",
  }},
  { kind: "figure", src: "/assets/renders/render-pdu-aeria.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Vista aèria del nou barri marítim previst pel PDU, amb el parc urbà i la renaturalització de la desembocadura del Besòs.",
      es: "Vista aérea del nuevo barrio marítimo previsto por el PDU, con el parque urbano y la renaturalización de la desembocadura del Besòs.",
      en: "Aerial view of the new seafront district envisaged by the PDU, with the urban park and the renaturalization of the Besòs mouth.",
    },
    source: { ca: "Consorci del Besòs · Render del PDU", es: "Consorci del Besòs · Render del PDU", en: "Consorci del Besòs · PDU rendering" },
  },
  { kind: "stats", head: { ca: "El PDU en xifres", es: "El PDU en cifras", en: "The PDU in figures" },
    items: [
      { num: "32", unit: "ha",
        label: { ca: "Àmbit de transformació", es: "Ámbito de transformación", en: "Transformation area" },
        desc:  { ca: "Front marítim entre Sant Adrià i Badalona.", es: "Frente marítimo entre Sant Adrià y Badalona.", en: "Seafront between Sant Adrià and Badalona." } },
      { num: "10", unit: "ha",
        label: { ca: "Parc urbà", es: "Parque urbano", en: "Urban park" },
        desc:  { ca: "Amb renaturalització de la desembocadura.", es: "Con renaturalización de la desembocadura.", en: "With renaturalization of the river mouth." } },
      { num: "1.783",
        label: { ca: "Habitatges", es: "Viviendas", en: "Homes" },
        desc:  { ca: "Un 40 % de protecció oficial (HPO).", es: "Un 40 % de protección oficial (HPO).", en: "40 % officially protected (HPO)." } },
      { num: "100.000", unit: "m²",
        label: { ca: "Activitat econòmica", es: "Actividad económica", en: "Economic activity" },
        desc:  { ca: "Sostre destinat a nous usos productius.", es: "Techo destinado a nuevos usos productivos.", en: "Floorspace for new productive uses." } },
    ],
  },
  { kind: "section", t: { ca: "Objectius del PDU", es: "Objetivos del PDU", en: "PDU objectives" } },
  { kind: "list",
    items: [
      { t: {
        ca: "**Integrar** aquest sector del front marítim amb la resta del litoral metropolità nord, amb un model d'ocupació del sòl compacte i una densitat raonablement alta, per permetre tipologies urbanes més eficients que fomentin una riquesa i diversitat més grans en les relacions socials i econòmiques.",
        es: "**Integrar** este sector del frente marítimo con el resto del litoral metropolitano norte, con un modelo de ocupación del suelo compacto y una densidad razonablemente alta, para permitir tipologías urbanas más eficientes que fomenten una riqueza y diversidad mayores en las relaciones sociales y económicas.",
        en: "**Integrate** this stretch of seafront with the rest of the northern metropolitan coast, through compact land use and reasonably high density, enabling more efficient urban typologies that foster richer, more diverse social and economic life.",
      }},
      { t: {
        ca: "**Incorporar el patrimoni industrial** al teixit urbà de nova creació per destinar-lo a nous usos.",
        es: "**Incorporar el patrimonio industrial** al tejido urbano de nueva creación para destinarlo a nuevos usos.",
        en: "**Incorporate the industrial heritage** into the newly created urban fabric and give it new uses.",
      }},
      { t: {
        ca: "**Garantir** a la ciutadania l'accés a l'habitatge assequible en un entorn saludable.",
        es: "**Garantizar** a la ciudadanía el acceso a la vivienda asequible en un entorno saludable.",
        en: "**Guarantee** citizens access to affordable housing in a healthy environment.",
      }},
      { t: {
        ca: "**Construir una xarxa** amb els espais lliures actuals i els de nova creació per fomentar la connexió entre el riu Besòs i el mar, i la continuïtat de tot el front litoral nord entre el Port de Barcelona i Montgat, potenciant la conservació i millora de la biodiversitat.",
        es: "**Construir una red** con los espacios libres actuales y los de nueva creación para fomentar la conexión entre el río Besòs y el mar, y la continuidad de todo el frente litoral norte entre el Puerto de Barcelona y Montgat, potenciando la conservación y mejora de la biodiversidad.",
        en: "**Build a network** of existing and new open spaces to connect the Besòs river with the sea and give continuity to the whole northern coastal front between the Port of Barcelona and Montgat, boosting the conservation and improvement of biodiversity.",
      }},
      { t: {
        ca: "**Establir un model de mobilitat sostenible**, atenent el transport públic, la garantia de l'accessibilitat universal i la regulació de l'aparcament.",
        es: "**Establecer un modelo de movilidad sostenible**, atendiendo al transporte público, la garantía de la accesibilidad universal y la regulación del aparcamiento.",
        en: "**Establish a sustainable mobility model** covering public transport, guaranteed universal accessibility and parking regulation.",
      }},
      { t: {
        ca: "**Incorporar la dimensió climàtica** en la planificació, contemplant estratègies per incrementar la resiliència envers escenaris climàtics futurs, com l'ascens del nivell del mar.",
        es: "**Incorporar la dimensión climática** en la planificación, contemplando estrategias para incrementar la resiliencia ante escenarios climáticos futuros, como el ascenso del nivel del mar.",
        en: "**Build in the climate dimension**, with strategies to increase resilience to future climate scenarios such as sea-level rise.",
      }},
    ],
  },
  { kind: "figure", src: "/assets/renders/render-parc-aeria.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "El parc urbà de 10 hectàrees previst entre les xemeneies i el mar.",
      es: "El parque urbano de 10 hectáreas previsto entre las chimeneas y el mar.",
      en: "The planned 10-hectare urban park between the chimneys and the sea.",
    },
    source: { ca: "Consorci del Besòs · Render del PDU", es: "Consorci del Besòs · Render del PDU", en: "Consorci del Besòs · PDU rendering" },
  },
  { kind: "section", t: { ca: "Més espai per a Sant Adrià i Badalona", es: "Más espacio para Sant Adrià y Badalona", en: "More space for Sant Adrià and Badalona" } },
  { kind: "p", t: {
    ca: "**3X vol dir més espai** per a Sant Adrià i Badalona. El nou barri marítim de les Tres Xemeneies recuperarà un espai històricament degradat.",
    es: "**3X quiere decir más espacio** para Sant Adrià y Badalona. El nuevo barrio marítimo de las Tres Chimeneas recuperará un espacio históricamente degradado.",
    en: "**3X means more space** for Sant Adrià and Badalona. The new Three Chimneys seafront district will reclaim a historically degraded area.",
  }},
  { kind: "list", head: { ca: "Objectius estratègics", es: "Objetivos estratégicos", en: "Strategic objectives" },
    items: [
      { k: { ca: "Habitatge assequible", es: "Vivienda asequible", en: "Affordable housing" }, t: {
        ca: "**1.783 habitatges** totals, amb un **40 % de protecció oficial** (HPO).",
        es: "**1.783 viviendas** totales, con un **40 % de protección oficial** (HPO).",
        en: "**1,783 homes** in total, **40 % officially protected** (HPO).",
      }},
      { k: { ca: "Mobilitat sostenible", es: "Movilidad sostenible", en: "Sustainable mobility" }, t: {
        ca: "Prioritat absoluta per a **vianants i bicicletes**, amb integració de bus, tramvia i tren.",
        es: "Prioridad absoluta para **peatones y bicicletas**, con integración de bus, tranvía y tren.",
        en: "Absolute priority for **pedestrians and bicycles**, with bus, tram and rail integration.",
      }},
      { k: { ca: "Sostenibilitat", es: "Sostenibilidad", en: "Sustainability" }, t: {
        ca: "Estratègies per afrontar l'**ascens del nivell del mar** i recuperació de la biodiversitat litoral.",
        es: "Estrategias para afrontar el **ascenso del nivel del mar** y recuperación de la biodiversidad litoral.",
        en: "Strategies to face **sea-level rise** and to restore coastal biodiversity.",
      }},
    ],
  },
  { kind: "figure", src: "/assets/renders/render-parc-cami.jpg", num: "03", ratio: "wide",
    desc: {
      ca: "Recorregut de vianants previst entre el nou barri i la platja.",
      es: "Recorrido peatonal previsto entre el nuevo barrio y la playa.",
      en: "Planned pedestrian route between the new district and the beach.",
    },
    source: { ca: "Consorci del Besòs · Render del PDU", es: "Consorci del Besòs · Render del PDU", en: "Consorci del Besòs · PDU rendering" },
  },
];

export const ARTICLE_MEDIA_CITY = [
  { kind: "section", t: { ca: "El projecte tractor", es: "El proyecto tractor", en: "The driving project" } },
  { kind: "p", lead: true, t: {
    ca: "El gran projecte tractor que donarà vida al recinte patrimonial és el **Catalunya Media City**. Aquest hub transformarà l'emblemàtica **Nau de Turbines** — un espai de **22.600 m²** adquirit per la Generalitat el 2023 — en un centre de referència mundial en producció audiovisual, videojocs i cultura digital.",
    es: "El gran proyecto tractor que dará vida al recinto patrimonial es el **Catalunya Media City**. Este hub transformará la emblemática **Nave de Turbinas** — un espacio de **22.600 m²** adquirido por la Generalitat en 2023 — en un centro de referencia mundial en producción audiovisual, videojuegos y cultura digital.",
    en: "The great driving project that will bring the heritage site to life is **Catalunya Media City**. The hub will turn the emblematic **Turbine Hall** — a **22,600 m²** space acquired by the Generalitat in 2023 — into a world-class centre for audiovisual production, video games and digital culture.",
  }},
  { kind: "figure", src: "/assets/renders/render-turbines-int.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "Interior de la Nau de Turbines segons el projecte guanyador: un contenidor flexible d'usos que conserva l'estructura original.",
      es: "Interior de la Nave de Turbinas según el proyecto ganador: un contenedor flexible de usos que conserva la estructura original.",
      en: "Interior of the Turbine Hall in the winning design: a flexible container of uses retaining the original structure.",
    },
    source: { ca: "Garcés De Seta Bonet + Marvel · Catalunya Media City", es: "Garcés De Seta Bonet + Marvel · Catalunya Media City", en: "Garcés De Seta Bonet + Marvel · Catalunya Media City" },
  },
  { kind: "list", head: { ca: "La primera inversió estratègica · 60 M€", es: "La primera inversión estratégica · 60 M€", en: "The first strategic investment · €60 M" },
    items: [
      { k: "01", t: {
        ca: "**Rehabilitació i ampliació de la Nau de Turbines**: el cor del projecte a Sant Adrià.",
        es: "**Rehabilitación y ampliación de la Nave de Turbinas**: el corazón del proyecto en Sant Adrià.",
        en: "**Refurbishment and extension of the Turbine Hall**: the heart of the project in Sant Adrià.",
      }},
      { k: "02", t: {
        ca: "**Infraestructura de producció**: ampliació de dos platós al Parc Audiovisual de Catalunya (Terrassa).",
        es: "**Infraestructura de producción**: ampliación de dos platós en el Parc Audiovisual de Catalunya (Terrassa).",
        en: "**Production infrastructure**: expansion of two sound stages at the Parc Audiovisual de Catalunya (Terrassa).",
      }},
      { k: "03", t: {
        ca: "**Adquisició de sòl** destinat a l'activitat econòmica vinculada al sector audiovisual al Besòs.",
        es: "**Adquisición de suelo** destinado a la actividad económica vinculada al sector audiovisual en el Besòs.",
        en: "**Land acquisition** for economic activity linked to the audiovisual sector at the Besòs.",
      }},
    ],
  },
  { kind: "section", t: { ca: "Un ecosistema cultural i científic", es: "Un ecosistema cultural y científico", en: "A cultural and scientific ecosystem" } },
  { kind: "p", t: {
    ca: "La Nau de Turbines combinarà un espai per a la **formació** i un **centre cultural i d'exhibició** que faci difusió de les darreres tendències audiovisuals i digitals, i serà un referent d'excel·lència per a la recerca i la innovació.",
    es: "La Nave de Turbinas combinará un espacio para la **formación** y un **centro cultural y de exhibición** que difunda las últimas tendencias audiovisuales y digitales, y será un referente de excelencia para la investigación y la innovación.",
    en: "The Turbine Hall will combine a space for **training** with a **cultural and exhibition centre** showcasing the latest audiovisual and digital trends, and will be a benchmark of excellence for research and innovation.",
  }},
  { kind: "p", t: {
    ca: "El projecte CMC neix en un moment en què totes les disciplines del coneixement s'hibriden i s'interconnecten, i l'audiovisual ocupa un lloc central a les vides de la gent. Molts d'aquests llenguatges tot just comencen a caminar ara i **dominaran la cultura popular els propers segles**.",
    es: "El proyecto CMC nace en un momento en que todas las disciplinas del conocimiento se hibridan e interconectan, y el audiovisual ocupa un lugar central en las vidas de la gente. Muchos de estos lenguajes apenas empiezan a caminar ahora y **dominarán la cultura popular los próximos siglos**.",
    en: "The CMC project is born at a moment when all disciplines of knowledge are hybridizing and interconnecting, and the audiovisual sits at the centre of people's lives. Many of these languages are only taking their first steps now and **will dominate popular culture for centuries to come**.",
  }},
  { kind: "section", t: { ca: "El concurs arquitectònic", es: "El concurso arquitectónico", en: "The architectural competition" } },
  { kind: "p", t: {
    ca: "El **2024** la Generalitat va convocar un concurs arquitectònic per al projecte d'adequació i ampliació de la Nau de Turbines. S'hi van presentar **26 avantprojectes**, dels quals **cinc** van passar a la segona volta.",
    es: "En **2024** la Generalitat convocó un concurso arquitectónico para el proyecto de adecuación y ampliación de la Nave de Turbinas. Se presentaron **26 anteproyectos**, de los cuales **cinco** pasaron a la segunda vuelta.",
    en: "In **2024** the Generalitat launched an architectural competition for the adaptation and extension of the Turbine Hall. **26 preliminary designs** were submitted, of which **five** reached the second round.",
  }},
  { kind: "p", t: {
    ca: "Finalment es va adjudicar la redacció del projecte a la UTE **Garcés De Seta Bonet arquitectes** + **Marvel Architects, Landscape Architects, Urban Designers**. La seva proposta tècnica, *E la nave va*, planteja respectar els trets patrimonials fonamentals de l'edifici i posar-los en valor amb el desplegament dels usos funcionals.",
    es: "Finalmente se adjudicó la redacción del proyecto a la UTE **Garcés De Seta Bonet arquitectes** + **Marvel Architects, Landscape Architects, Urban Designers**. Su propuesta técnica, *E la nave va*, plantea respetar los rasgos patrimoniales fundamentales del edificio y ponerlos en valor con el despliegue de los usos funcionales.",
    en: "The commission went to the joint venture **Garcés De Seta Bonet arquitectes** + **Marvel Architects, Landscape Architects, Urban Designers**. Their technical proposal, *E la nave va*, sets out to respect the building's essential heritage features and bring them into their own through the new functional uses.",
  }},
  { kind: "stats", head: { ca: "El concurs · 2024", es: "El concurso · 2024", en: "The competition · 2024" },
    items: [
      { num: "26",
        label: { ca: "Avantprojectes", es: "Anteproyectos", en: "Entries" },
        desc:  { ca: "Presentats al concurs de la Generalitat.", es: "Presentados al concurso de la Generalitat.", en: "Submitted to the Generalitat's competition." } },
      { num: "5",
        label: { ca: "Finalistes", es: "Finalistas", en: "Finalists" },
        desc:  { ca: "Van passar a la segona volta.", es: "Pasaron a la segunda vuelta.", en: "Reached the second round." } },
      { num: "22.600", unit: "m²",
        label: { ca: "Nau de Turbines", es: "Nave de Turbinas", en: "Turbine Hall" },
        desc:  { ca: "Adquirits per la Generalitat el 2023.", es: "Adquiridos por la Generalitat en 2023.", en: "Acquired by the Generalitat in 2023." } },
      { num: "60", unit: "M€",
        label: { ca: "Primera inversió", es: "Primera inversión", en: "First investment" },
        desc:  { ca: "Atorgada per l'Estat a la Generalitat.", es: "Otorgada por el Estado a la Generalitat.", en: "Granted by the State to the Generalitat." } },
    ],
  },
  { kind: "p", t: {
    ca: "El cor conceptual de la proposta gira entorn de la conversió d'un espai industrial obsolet en un **ecosistema cultural, científic i audiovisual d'avantguarda**, tot mantenint la identitat arquitectònica de l'antiga central tèrmica.",
    es: "El corazón conceptual de la propuesta gira en torno a la conversión de un espacio industrial obsoleto en un **ecosistema cultural, científico y audiovisual de vanguardia**, manteniendo la identidad arquitectónica de la antigua central térmica.",
    en: "The proposal's conceptual core is the conversion of an obsolete industrial space into a **cutting-edge cultural, scientific and audiovisual ecosystem**, while keeping the architectural identity of the old power plant.",
  }},
  { kind: "p", t: {
    ca: "La nau principal es conserva i es reinterpreta com un **contenidor flexible d'usos**, mentre que el nou cos afegit — lleuger, lluminós i sostenible — acull espais experimentals, laboratoris, sales immersives, platós i zones de recerca i d'innovació.",
    es: "La nave principal se conserva y se reinterpreta como un **contenedor flexible de usos**, mientras que el nuevo cuerpo añadido — ligero, luminoso y sostenible — acoge espacios experimentales, laboratorios, salas inmersivas, platós y zonas de investigación e innovación.",
    en: "The main hall is preserved and reinterpreted as a **flexible container of uses**, while the new added volume — light, luminous and sustainable — houses experimental spaces, laboratories, immersive rooms, sound stages and areas for research and innovation.",
  }},
  { kind: "figure", src: "/assets/renders/render-turbines-ext.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "El nou cos afegit, lleuger i lluminós, al costat de la nau patrimonial conservada.",
      es: "El nuevo cuerpo añadido, ligero y luminoso, junto a la nave patrimonial conservada.",
      en: "The new light, luminous volume alongside the preserved heritage hall.",
    },
    source: { ca: "Garcés De Seta Bonet + Marvel · Catalunya Media City", es: "Garcés De Seta Bonet + Marvel · Catalunya Media City", en: "Garcés De Seta Bonet + Marvel · Catalunya Media City" },
  },
  { kind: "p", t: {
    ca: "La proposta presenta també una elaborada estratègia mediambiental i d'integració al paisatge, així com un discurs potent sobre el valor patrimonial de l'edifici: conserva **buits originals, estructura i ritme** de la nau de turbines i els integra en una nova narrativa arquitectònica que vincula el passat industrial amb el futur digital del Besòs.",
    es: "La propuesta presenta también una elaborada estrategia medioambiental y de integración en el paisaje, así como un discurso potente sobre el valor patrimonial del edificio: conserva **huecos originales, estructura y ritmo** de la nave de turbinas y los integra en una nueva narrativa arquitectónica que vincula el pasado industrial con el futuro digital del Besòs.",
    en: "The proposal also sets out an elaborate environmental and landscape-integration strategy, and a powerful argument about the building's heritage value: it keeps the turbine hall's **original openings, structure and rhythm** and folds them into a new architectural narrative linking the industrial past to the Besòs's digital future.",
  }},
  { kind: "p", t: {
    ca: "El conjunt es concep com una **nova centralitat metropolitana**, capaç de connectar barris, ciutats i disciplines, consolidant el Catalunya Media City com un node clau per a la recerca, la creació i l'experimentació tecnològica.",
    es: "El conjunto se concibe como una **nueva centralidad metropolitana**, capaz de conectar barrios, ciudades y disciplinas, consolidando el Catalunya Media City como un nodo clave para la investigación, la creación y la experimentación tecnológica.",
    en: "The complex is conceived as a **new metropolitan centrality**, able to connect neighbourhoods, cities and disciplines, consolidating Catalunya Media City as a key node for research, creation and technological experimentation.",
  }},
  { kind: "list", head: { ca: "Àmbits d'actuació", es: "Ámbitos de actuación", en: "Areas of action" },
    items: [
      { k: { ca: "Formació", es: "Formación", en: "Training" }, t: {
        ca: "Impuls de programes formatius especialitzats, connectats amb les necessitats del sector i orientats a la generació de talent qualificat, gràcies als estudis de Formació Professional i universitaris.",
        es: "Impulso de programas formativos especializados, conectados con las necesidades del sector y orientados a la generación de talento cualificado, gracias a los estudios de Formación Profesional y universitarios.",
        en: "Specialized training programmes connected to the sector's needs and aimed at generating qualified talent, through vocational and university studies.",
      }},
      { k: { ca: "Innovació i empresa", es: "Innovación y empresa", en: "Innovation and business" }, t: {
        ca: "Entorn favorable al desenvolupament empresarial, la transferència de coneixement i la col·laboració entre empreses, centres de recerca i institucions.",
        es: "Entorno favorable al desarrollo empresarial, la transferencia de conocimiento y la colaboración entre empresas, centros de investigación e instituciones.",
        en: "An environment favourable to business development, knowledge transfer and collaboration between companies, research centres and institutions.",
      }},
      { k: { ca: "Producció i creació", es: "Producción y creación", en: "Production and creation" }, t: {
        ca: "Recerca i promoció de nous continguts, formats, llenguatges i narratives vinculades a l'audiovisual, el digital i el videojoc.",
        es: "Investigación y promoción de nuevos contenidos, formatos, lenguajes y narrativas vinculadas al audiovisual, el digital y el videojuego.",
        en: "Research into and promotion of new content, formats, languages and narratives linked to the audiovisual, the digital and gaming.",
      }},
      { k: { ca: "Experiència i ciutadania", es: "Experiencia y ciudadanía", en: "Experience and citizenship" }, t: {
        ca: "Desenvolupament d'espais i activitats que connectin el projecte amb la ciutadania, fomentant l'accés a la cultura digital i a nous formats creatius.",
        es: "Desarrollo de espacios y actividades que conecten el proyecto con la ciudadanía, fomentando el acceso a la cultura digital y a nuevos formatos creativos.",
        en: "Spaces and activities that connect the project with citizens, encouraging access to digital culture and new creative formats.",
      }},
    ],
  },
  { kind: "quote",
    t: {
      ca: "De cremar carbó per moure la indústria del segle XX a **generar energia creativa** per liderar l'economia digital del segle XXI.",
      es: "De quemar carbón para mover la industria del siglo XX a **generar energía creativa** para liderar la economía digital del siglo XXI.",
      en: "From burning coal to drive 20th-century industry to **generating creative energy** to lead the 21st-century digital economy.",
    },
    cite: {
      ca: "— Catalunya Media City",
      es: "— Catalunya Media City",
      en: "— Catalunya Media City",
    },
  },
  { kind: "p", t: {
    ca: "Amb aquesta transformació, les Tres Xemeneies completen el seu cercle vital. El passat industrial esdevé així el fonament d'un **futur ple d'oportunitats** per a la ciutadania.",
    es: "Con esta transformación, las Tres Chimeneas completan su círculo vital. El pasado industrial se convierte así en el fundamento de un **futuro lleno de oportunidades** para la ciudadanía.",
    en: "With this transformation the Three Chimneys complete their life cycle. The industrial past becomes the foundation of a **future full of opportunity** for citizens.",
  }},
];

export const ARTICLE_MEMORIA = [
  { kind: "p", lead: true, t: {
    ca: "L'antiga **sala de control** acull l'espai de memòria: un lloc per mirar de prop la fàbrica en funcionament, el treball que la va fer possible i el procés de desmantellament.",
    es: "La antigua **sala de control** acoge el espacio de memoria: un lugar para mirar de cerca la fábrica en funcionamiento, el trabajo que la hizo posible y el proceso de desmantelamiento.",
    en: "The old **control room** houses the memory space: a place to look closely at the plant at work, the labour that made it possible, and the dismantling that followed.",
  }},
  { kind: "figure", src: "/assets/fotografies/mp-1.jpg", num: "01", ratio: "wide",
    desc: {
      ca: "La sala de control de la central, avui espai de memòria.",
      es: "La sala de control de la central, hoy espacio de memoria.",
      en: "The plant's control room, today a memory space.",
    },
    source: { ca: "Arxiu 3CAT · Consorci del Besòs", es: "Archivo 3CAT · Consorci del Besòs", en: "3CAT Archive · Consorci del Besòs" },
  },
  { kind: "section", t: { ca: "La fàbrica en funcionament", es: "La fábrica en funcionamiento", en: "The plant at work" } },
  { kind: "p", t: {
    ca: "Imatges de la central en diferents moments de la seva història: els quadres de comandament, la sala de turbines en plena activitat i els torns que van sostenir cinquanta anys de producció elèctrica ininterrompuda.",
    es: "Imágenes de la central en distintos momentos de su historia: los cuadros de mando, la sala de turbinas en plena actividad y los turnos que sostuvieron cincuenta años de producción eléctrica ininterrumpida.",
    en: "Images of the plant at different moments in its history: the control panels, the turbine hall in full activity, and the shifts that sustained fifty years of uninterrupted electrical production.",
  }},
  { kind: "figure", src: "/assets/fotografies/mp-3.jpg", num: "02", ratio: "wide",
    desc: {
      ca: "La sala de turbines en funcionament.",
      es: "La sala de turbinas en funcionamiento.",
      en: "The turbine hall in operation.",
    },
    source: { ca: "Arxiu 3CAT · Fons FECSA-Endesa", es: "Archivo 3CAT · Fondo FECSA-Endesa", en: "3CAT Archive · FECSA-Endesa collection" },
  },
  { kind: "section", t: { ca: "La demolició", es: "La demolición", en: "The demolition" } },
  { kind: "p", t: {
    ca: "El desmantellament de les instal·lacions no protegides va deixar en peu només allò que la ciutadania havia decidit conservar: les **tres xemeneies** i la **nau de turbines**.",
    es: "El desmantelamiento de las instalaciones no protegidas dejó en pie sólo aquello que la ciudadanía había decidido conservar: las **tres chimeneas** y la **nave de turbinas**.",
    en: "The dismantling of the unprotected facilities left standing only what citizens had decided to keep: the **three chimneys** and the **turbine hall**.",
  }},
  { kind: "figure", src: "/assets/fotografies/mp-5.jpg", num: "03", ratio: "wide",
    desc: {
      ca: "Procés de demolició de les instal·lacions no protegides.",
      es: "Proceso de demolición de las instalaciones no protegidas.",
      en: "Demolition of the unprotected facilities.",
    },
    source: { ca: "Arxiu Consorci del Besòs · Generalitat de Catalunya", es: "Archivo Consorci del Besòs · Generalitat de Catalunya", en: "Consorci del Besòs Archive · Generalitat de Catalunya" },
  },
  { kind: "list", head: { ca: "Per continuar consultant", es: "Para seguir consultando", en: "To explore further" },
    items: [
      { k: { ca: "Refugi antiaeri de Sant Adrià de Besòs", es: "Refugio antiaéreo de Sant Adrià de Besòs", en: "Sant Adrià de Besòs air-raid shelter" }, t: {
        ca: "Centre d'interpretació de la placeta Macià, sobre els bombardejos de la Guerra Civil al municipi.",
        es: "Centro de interpretación de la placeta Macià, sobre los bombardeos de la Guerra Civil en el municipio.",
        en: "Interpretation centre at placeta Macià, on the Civil War bombings of the town.",
      }},
      { k: { ca: "Filmoteca de Catalunya", es: "Filmoteca de Catalunya", en: "Filmoteca de Catalunya" }, t: {
        ca: "*Inauguració de la nova central tèrmica* (1968) i *Notas sobre el Besós* (1978).",
        es: "*Inauguración de la nueva central térmica* (1968) y *Notas sobre el Besós* (1978).",
        en: "*Inauguration of the new thermal plant* (1968) and *Notas sobre el Besós* (1978).",
      }},
      { k: { ca: "Badalona Comunicació", es: "Badalona Comunicació", en: "Badalona Comunicació" }, t: {
        ca: "Reportatge *ON/OFF: Les Tres Xemeneies* i la primera manifestació amb presència de dones.",
        es: "Reportaje *ON/OFF: Les Tres Xemeneies* y la primera manifestación con presencia de mujeres.",
        en: "Documentary *ON/OFF: Les Tres Xemeneies* and the first demonstration with women present.",
      }},
      { k: { ca: "RTVE · 3CAT", es: "RTVE · 3CAT", en: "RTVE · 3CAT" }, t: {
        ca: "NO-DO de 1968 a RTVE Play i *Xemeneies: Central Tèrmica de Sant Adrià* (Fonamentals).",
        es: "NO-DO de 1968 en RTVE Play y *Xemeneies: Central Tèrmica de Sant Adrià* (Fonamentals).",
        en: "The 1968 NO-DO newsreel on RTVE Play and *Xemeneies: Central Tèrmica de Sant Adrià* (Fonamentals).",
      }},
    ],
  },
  { kind: "quote",
    t: {
      ca: "Un segle de **producció elèctrica i mobilització veïnal** al marge esquerre del Besòs.",
      es: "Un siglo de **producción eléctrica y movilización vecinal** en el margen izquierdo del Besòs.",
      en: "A century of **electrical production and neighbourhood mobilization** on the left bank of the Besòs.",
    },
    cite: {
      ca: "— Les Tres Xemeneies · 1913 — 2025",
      es: "— Las Tres Chimeneas · 1913 — 2025",
      en: "— The Three Chimneys · 1913 — 2025",
    },
  },
];
