// content-meta.jsx — Traduccions UI + metadades dels capítols (CA / ES / EN)

export const UI = {
  ca: {
    site: "Tres Xemeneies",
    chapter: "Capítol",
    chapters: "capítols",
    of: "de",
    prev: "Anterior",
    next: "Següent",
    landing: "Landing",
    landingFull: "Menú principal",
    indexTitle: "Índex",
    status: { reading: "Llegint", available: "Disponible", menu: "Menú", soon: "Aviat" },
    minRead: "min de lectura",
    backLabel: "Tornar al menú principal",
    menuLabel: "Obrir índex de capítols",
    keepReading: "Continua llegint",
    readNext: "Llegir el capítol",
    next2Label: "Següent capítol",
    skipToContent: "Saltar al contingut",
    close: "Tancar",
    langGroup: "Selector d'idioma",
    pagerLabel: "Navegació entre capítols",
    mapLink: "On sóc? · Mapa interactiu",
    a11y: { title: "Declaració d'accessibilitat" },
  },
  es: {
    site: "Tres Xemeneies",
    chapter: "Capítulo",
    chapters: "capítulos",
    of: "de",
    prev: "Anterior",
    next: "Siguiente",
    landing: "Landing",
    landingFull: "Menú principal",
    indexTitle: "Índice",
    status: { reading: "Leyendo", available: "Disponible", menu: "Menú", soon: "Pronto" },
    minRead: "min de lectura",
    backLabel: "Volver al menú principal",
    menuLabel: "Abrir índice de capítulos",
    keepReading: "Sigue leyendo",
    readNext: "Leer el capítulo",
    next2Label: "Siguiente capítulo",
    skipToContent: "Saltar al contenido",
    close: "Cerrar",
    langGroup: "Selector de idioma",
    pagerLabel: "Navegación entre capítulos",
    mapLink: "¿Dónde estoy? · Mapa interactivo",
    a11y: { title: "Declaración de accesibilidad" },
  },
  en: {
    site: "Tres Xemeneies",
    chapter: "Chapter",
    chapters: "chapters",
    of: "of",
    prev: "Previous",
    next: "Next",
    landing: "Landing",
    landingFull: "Main menu",
    indexTitle: "Index",
    status: { reading: "Reading", available: "Available", menu: "Menu", soon: "Soon" },
    minRead: "min read",
    backLabel: "Back to main menu",
    menuLabel: "Open chapter index",
    keepReading: "Keep reading",
    readNext: "Read chapter",
    next2Label: "Next chapter",
    skipToContent: "Skip to content",
    close: "Close",
    langGroup: "Language selector",
    pagerLabel: "Chapter navigation",
    mapLink: "Where am I? · Interactive map",
    a11y: { title: "Accessibility statement" },
  },
};

export const CHAPTERS = [
  {
    slug: "icona", n: "01",
    title: {
      ca: { main: "La icona", em: "del litoral" },
      es: { main: "El icono", em: "del litoral" },
      en: { main: "The landmark", em: "of the coast" },
    },
    deck: {
      ca: "Un dels monuments industrials més alts de la Mediterrània, avui el cor d'una transformació de 32 hectàrees.",
      es: "Uno de los monumentos industriales más altos del Mediterráneo, hoy el corazón de una transformación de 32 hectáreas.",
      en: "One of the tallest industrial monuments in the Mediterranean, today the heart of a 32-hectare transformation.",
    },
    meta: {
      period: { label: { ca: "Alçada", es: "Altura", en: "Height" },              v: "200 m" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "3 min", es: "3 min", en: "3 min" } },
      place:  { label: { ca: "Sector", es: "Sector", en: "Sector" },              v: "32 ha" },
      source: { label: { ca: "Protecció", es: "Protección", en: "Protection" },   v: "BCIL · 2016" },
    },
  },
  {
    slug: "origens", n: "02",
    title: {
      ca: { main: "Els", em: "orígens" },
      es: { main: "Los", em: "orígenes" },
      en: { main: "The", em: "origins" },
    },
    deck: {
      ca: "**El bressol de l'energia.** La primera central tèrmica del Besòs i la xarxa que va unir el Pirineu amb el mar.",
      es: "**La cuna de la energía.** La primera central térmica del Besòs y la red que unió el Pirineo con el mar.",
      en: "**The cradle of energy.** The first Besòs thermal plant and the grid that linked the Pyrenees to the sea.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },            v: "1912 — 1923" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Arquitecte", es: "Arquitecto", en: "Architect" },   v: "Eduard Ferrés" },
      source: { label: { ca: "Fons documental", es: "Fondo documental", en: "Archive" }, v: { ca: "ANC · FECSA-Endesa", es: "ANC · FECSA-Endesa", en: "ANC · FECSA-Endesa" } },
    },
  },
  {
    slug: "guerres", n: "03",
    title: {
      ca: { main: "L'energia en", em: "temps de guerres" },
      es: { main: "La energía en", em: "tiempos de guerra" },
      en: { main: "Energy in", em: "times of war" },
    },
    deck: {
      ca: "**Objectiu militar.** Del bloqueig del carbó al bombardeig del 13 de novembre de 1938.",
      es: "**Objetivo militar.** Del bloqueo del carbón al bombardeo del 13 de noviembre de 1938.",
      en: "**A military target.** From the coal blockade to the bombing of 13 November 1938.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },            v: "1914 — 1954" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Bombardeig", es: "Bombardeo", en: "Bombing" },      v: { ca: "16 morts", es: "16 muertos", en: "16 dead" } },
      source: { label: { ca: "Fons documental", es: "Fondo documental", en: "Archive" }, v: { ca: "ANC · FECSA-Endesa", es: "ANC · FECSA-Endesa", en: "ANC · FECSA-Endesa" } },
    },
  },
  {
    slug: "brutalisme", n: "04",
    title: {
      ca: { main: "L'era", em: "brutalista" },
      es: { main: "La era", em: "brutalista" },
      en: { main: "The brutalist", em: "era" },
    },
    deck: {
      ca: "**Tècnica, contaminació i protesta.** La construcció de les Tres Xemeneies, i els conflictes ambientals que van marcar el territori.",
      es: "**Técnica, contaminación y protesta.** La construcción de las Tres Chimeneas, y los conflictos ambientales que marcaron el territorio.",
      en: "**Engineering, pollution and protest.** The building of the Three Chimneys, and the environmental conflicts that marked the area.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },            v: "1959 — 1983" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "8 min", es: "8 min", en: "8 min" } },
      place:  { label: { ca: "Potència", es: "Potencia", en: "Power" },           v: "1.050 MW" },
      source: { label: { ca: "Operador", es: "Operador", en: "Operator" },        v: "FECSA" },
    },
  },
  {
    slug: "lluita", n: "05",
    title: {
      ca: { main: "La lluita obrera", em: "i la conservació" },
      es: { main: "La lucha obrera", em: "y la conservación" },
      en: { main: "Labour struggle", em: "and conservation" },
    },
    deck: {
      ca: "**Un monument a la dignitat laboral.** De la mort de Manuel Fernández Márquez a la consulta ciutadana de 2008.",
      es: "**Un monumento a la dignidad laboral.** De la muerte de Manuel Fernández Márquez a la consulta ciudadana de 2008.",
      en: "**A monument to labour dignity.** From the death of Manuel Fernández Márquez to the 2008 citizens' consultation.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },            v: "1973 — 2016" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Consulta 2008", es: "Consulta 2008", en: "2008 consultation" }, v: { ca: "82,2 % a favor", es: "82,2 % a favor", en: "82.2 % in favour" } },
      source: { label: { ca: "Protecció", es: "Protección", en: "Protection" },   v: "BCIL · 2016" },
    },
  },
  {
    slug: "pdu", n: "06",
    title: {
      ca: { main: "El PDU", em: "Tres Xemeneies" },
      es: { main: "El PDU", em: "Tres Xemeneies" },
      en: { main: "The", em: "Tres Xemeneies plan" },
    },
    deck: {
      ca: "**Un nou model de ciutat.** 32 hectàrees, un parc de 10 ha i més de 185.000 m² d'habitatge al front marítim.",
      es: "**Un nuevo modelo de ciudad.** 32 hectáreas, un parque de 10 ha y más de 185.000 m² de vivienda en el frente marítimo.",
      en: "**A new model of city.** 32 hectares, a 10-ha park and over 185,000 m² of housing on the seafront.",
    },
    meta: {
      period: { label: { ca: "Aprovat", es: "Aprobado", en: "Approved" },         v: "2023" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "7 min", es: "7 min", en: "7 min" } },
      place:  { label: { ca: "Superfície", es: "Superficie", en: "Surface" },     v: "32 ha" },
      source: { label: { ca: "Admin. actuant", es: "Admin. actuante", en: "Acting body" }, v: { ca: "Consorci del Besòs", es: "Consorci del Besòs", en: "Consorci del Besòs" } },
    },
  },
  {
    slug: "media-city", n: "07",
    title: {
      ca: { main: "Catalunya", em: "Media City" },
      es: { main: "Catalunya", em: "Media City" },
      en: { main: "Catalunya", em: "Media City" },
    },
    deck: {
      ca: "**El hub audiovisual del futur.** La Nau de Turbines, més de 40.000 m² per a la producció, els videojocs i la cultura digital.",
      es: "**El hub audiovisual del futuro.** La Nave de Turbinas, más de 40.000 m² para la producción, los videojuegos y la cultura digital.",
      en: "**The audiovisual hub of the future.** The Turbine Hall, over 40,000 m² for production, gaming and digital culture.",
    },
    meta: {
      period: { label: { ca: "Estat", es: "Estado", en: "Status" },               v: { ca: "En projecte", es: "En proyecto", en: "In design" } },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "7 min", es: "7 min", en: "7 min" } },
      place:  { label: { ca: "Arquitectes", es: "Arquitectos", en: "Architects" }, v: "GDSB + Marvel" },
      source: { label: { ca: "Inversió", es: "Inversión", en: "Investment" },     v: "60 M€" },
    },
  },
  {
    slug: "memoria", n: "08",
    title: {
      ca: { main: "L'espai", em: "de memòria" },
      es: { main: "El espacio", em: "de memoria" },
      en: { main: "The memory", em: "space" },
    },
    deck: {
      ca: "**La sala de control.** Imatges de la fàbrica en funcionament, el treball i la demolició.",
      es: "**La sala de control.** Imágenes de la fábrica en funcionamiento, el trabajo y la demolición.",
      en: "**The control room.** Images of the plant at work, of labour, and of the demolition.",
    },
    meta: {
      period: { label: { ca: "Cobreix", es: "Cubre", en: "Spans" },               v: "1913 — 2025" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },              v: { ca: "5 min", es: "5 min", en: "5 min" } },
      place:  { label: { ca: "Ubicació", es: "Ubicación", en: "Location" },       v: { ca: "Sala de control", es: "Sala de control", en: "Control room" } },
      source: { label: { ca: "Fons", es: "Fondos", en: "Archives" },              v: { ca: "3CAT · Consorci · Gencat", es: "3CAT · Consorci · Gencat", en: "3CAT · Consorci · Gencat" } },
    },
  },
];

