// content-meta.jsx — Traduccions UI + metadades dels capítols (CA / ES / EN)

export const UI = {
  ca: {
    site: "Tres Xemeneies",
    chapter: "Capítol",
    chapters: "capítols",
    of: "de",
    prev: "Anterior",
    next: "Següent",
    landing: "Landing",
    landingFull: "Menú principal",
    indexTitle: "Índex",
    status: { reading: "Llegint", available: "Disponible", menu: "Menú", soon: "Aviat" },
    minRead: "min de lectura",
    backLabel: "Tornar al menú principal",
    menuLabel: "Obrir índex de capítols",
    keepReading: "Continua llegint",
    readNext: "Llegir el capítol",
    next2Label: "Següent capítol",
    skipToContent: "Saltar al contingut",
    close: "Tancar",
    langGroup: "Selector d'idioma",
    pagerLabel: "Navegació entre capítols",
    mapLink: "Veure al mapa",
    a11y: { title: "Declaració d'accessibilitat" },
  },
  es: {
    site: "Tres Xemeneies",
    chapter: "Capítulo",
    chapters: "capítulos",
    of: "de",
    prev: "Anterior",
    next: "Siguiente",
    landing: "Landing",
    landingFull: "Menú principal",
    indexTitle: "Índice",
    status: { reading: "Leyendo", available: "Disponible", menu: "Menú", soon: "Pronto" },
    minRead: "min de lectura",
    backLabel: "Volver al menú principal",
    menuLabel: "Abrir índice de capítulos",
    keepReading: "Sigue leyendo",
    readNext: "Leer el capítulo",
    next2Label: "Siguiente capítulo",
    skipToContent: "Saltar al contenido",
    close: "Cerrar",
    langGroup: "Selector de idioma",
    pagerLabel: "Navegación entre capítulos",
    mapLink: "Ver en el mapa",
    a11y: { title: "Declaración de accesibilidad" },
  },
  en: {
    site: "Tres Xemeneies",
    chapter: "Chapter",
    chapters: "chapters",
    of: "of",
    prev: "Previous",
    next: "Next",
    landing: "Landing",
    landingFull: "Main menu",
    indexTitle: "Index",
    status: { reading: "Reading", available: "Available", menu: "Menu", soon: "Soon" },
    minRead: "min read",
    backLabel: "Back to main menu",
    menuLabel: "Open chapter index",
    keepReading: "Keep reading",
    readNext: "Read chapter",
    next2Label: "Next chapter",
    skipToContent: "Skip to content",
    close: "Close",
    langGroup: "Language selector",
    pagerLabel: "Chapter navigation",
    mapLink: "View on map",
    a11y: { title: "Accessibility statement" },
  },
};

export const CHAPTERS = [
  {
    slug: "origens", n: "01",
    title: {
      ca: { main: "Els", em: "Orígens" },
      es: { main: "Los", em: "Orígenes" },
      en: { main: "The", em: "Origins" },
    },
    deck: {
      ca: "**De les hortes a la indústria.** Un segle de producció elèctrica al marge esquerre del Besòs.",
      es: "**De las huertas a la industria.** Un siglo de producción eléctrica en el margen izquierdo del Besòs.",
      en: "**From orchards to industry.** A century of electrical production on the left bank of the Besòs.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },           v: "1913 — 1954" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Ubicació", es: "Ubicación", en: "Location" },      v: "Sant Adrià de Besòs" },
      source: { label: { ca: "Fons documental", es: "Fondo documental", en: "Archive" }, v: { ca: "Endesa · Hist.", es: "Endesa · Hist.", en: "Endesa · Hist." } },
    },
  },
  {
    slug: "produccio", n: "02",
    title: {
      ca: { main: "La", em: "producció" },
      es: { main: "La", em: "producción" },
      en: { main: "The", em: "production" },
    },
    deck: {
      ca: "**Cinquanta anys d'energia.** Tres blocs, mil cinquanta megawatts, una silueta que va encendre Catalunya.",
      es: "**Cincuenta años de energía.** Tres bloques, mil cincuenta megavatios, una silueta que encendió Cataluña.",
      en: "**Fifty years of energy.** Three blocks, 1,050 megawatts, a silhouette that powered Catalonia.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },           v: "1959 — 2011" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "7 min", es: "7 min", en: "7 min" } },
      place:  { label: { ca: "Potència", es: "Potencia", en: "Power" },          v: "1.050 MW" },
      source: { label: { ca: "Operadors", es: "Operadores", en: "Operators" },   v: "FECSA · Endesa" },
    },
  },
  {
    slug: "tancament", n: "03",
    title: {
      ca: { main: "El", em: "tancament" },
      es: { main: "El", em: "cierre" },
      en: { main: "The", em: "shutdown" },
    },
    deck: {
      ca: "**Obsolescència, contaminació i mercat.** Per què Endesa va aturar les turbines el 2011.",
      es: "**Obsolescencia, contaminación y mercado.** Por qué Endesa apagó las turbinas en 2011.",
      en: "**Obsolescence, pollution and market.** Why Endesa stopped the turbines in 2011.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },           v: "1983 — 2011" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "5 min", es: "5 min", en: "5 min" } },
      place:  { label: { ca: "Zona contaminada", es: "Zona contaminada", en: "Polluted zone" }, v: { ca: "1983", es: "1983", en: "1983" } },
      source: { label: { ca: "Tancament", es: "Cierre", en: "Closure" },         v: "2011" },
    },
  },
  {
    slug: "reivindicacio", n: "04",
    title: {
      ca: { main: "La", em: "reivindicació" },
      es: { main: "La", em: "reivindicación" },
      en: { main: "Citizen", em: "mobilization" },
    },
    deck: {
      ca: "**Mig segle de mobilització veïnal.** Del *polsim negre* del 1966 al BCIL del 2016.",
      es: "**Medio siglo de movilización vecinal.** Del *polvillo negro* de 1966 al BCIL de 2016.",
      en: "**Half a century of neighborhood action.** From the *black soot* of 1966 to the BCIL of 2016.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },           v: "1966 — 2016" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Referèndum", es: "Referéndum", en: "Referendum" }, v: { ca: "82 % a favor", es: "82 % a favor", en: "82 % in favor" } },
      source: { label: { ca: "Protecció", es: "Protección", en: "Protection" },  v: "BCIL · 2016" },
    },
  },
  {
    slug: "futur", n: "05",
    title: {
      ca: { main: "El projecte", em: "de futur" },
      es: { main: "El proyecto", em: "de futuro" },
      en: { main: "The future", em: "project" },
    },
    deck: {
      ca: "**32 hectàrees, un nou barri litoral.** El PDU i l'impuls de Catalunya Media City.",
      es: "**32 hectáreas, un nuevo barrio litoral.** El PDU y el impulso de Catalunya Media City.",
      en: "**32 hectares, a new seafront district.** The PDU and the push for Catalunya Media City.",
    },
    meta: {
      period: { label: { ca: "Període", es: "Período", en: "Period" },           v: "2018 — 2023" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "6 min", es: "6 min", en: "6 min" } },
      place:  { label: { ca: "Superfície", es: "Superficie", en: "Surface" },    v: "32 ha" },
      source: { label: { ca: "PDU aprovat", es: "PDU aprobado", en: "PDU approved" }, v: { ca: "2023", es: "2023", en: "2023" } },
    },
  },
  {
    slug: "nau-turbines", n: "06",
    title: {
      ca: { main: "La Nau de", em: "Turbines" },
      es: { main: "La Nave de", em: "Turbinas" },
      en: { main: "The Turbine", em: "Hall" },
    },
    deck: {
      ca: "**L'epicentre del hub audiovisual.** Formació, innovació i experiència dins la carcassa de la central.",
      es: "**El epicentro del hub audiovisual.** Formación, innovación y experiencia dentro de la carcasa de la central.",
      en: "**The audiovisual hub's epicenter.** Training, innovation and experience inside the plant's shell.",
    },
    meta: {
      period: { label: { ca: "Estat", es: "Estado", en: "Status" },              v: { ca: "En projecte", es: "En proyecto", en: "In design" } },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "4 min", es: "4 min", en: "4 min" } },
      place:  { label: { ca: "Arquitectes", es: "Arquitectos", en: "Architects" }, v: "GDSB + Marvel" },
      source: { label: { ca: "Promotor", es: "Promotor", en: "Promoter" },       v: "Catalunya Media City" },
    },
  },
  {
    slug: "memoria", n: "07",
    title: {
      ca: { main: "L'espai", em: "de memòria" },
      es: { main: "El espacio", em: "de memoria" },
      en: { main: "The memory", em: "space" },
    },
    deck: {
      ca: "**Un equipament dedicat a la memòria.** La industrialització, el treball i les reivindicacions ciutadanes.",
      es: "**Un equipamiento dedicado a la memoria.** La industrialización, el trabajo y las reivindicaciones ciudadanas.",
      en: "**An institution dedicated to memory.** Industrialization, labour and citizen struggles.",
    },
    meta: {
      period: { label: { ca: "Cobreix", es: "Cubre", en: "Spans" },              v: "1913 — 2025" },
      read:   { label: { ca: "Lectura", es: "Lectura", en: "Read" },             v: { ca: "5 min", es: "5 min", en: "5 min" } },
      place:  { label: { ca: "Tipus", es: "Tipo", en: "Type" },                  v: { ca: "Equipament cultural", es: "Equipamiento cultural", en: "Cultural facility" } },
      source: { label: { ca: "Programació", es: "Programación", en: "Programme" }, v: { ca: "3 vessants", es: "3 vertientes", en: "3 strands" } },
    },
  },
];